// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/proto/enclave.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DEPRECATED: type is ignored - sync behavior is automatic
type SyncJobRequest_SyncType int32

const (
	SyncJobRequest_INCREMENTAL SyncJobRequest_SyncType = 0
	SyncJobRequest_HISTORICAL  SyncJobRequest_SyncType = 1
	SyncJobRequest_FULL        SyncJobRequest_SyncType = 2
)

// Enum value maps for SyncJobRequest_SyncType.
var (
	SyncJobRequest_SyncType_name = map[int32]string{
		0: "INCREMENTAL",
		1: "HISTORICAL",
		2: "FULL",
	}
	SyncJobRequest_SyncType_value = map[string]int32{
		"INCREMENTAL": 0,
		"HISTORICAL":  1,
		"FULL":        2,
	}
)

func (x SyncJobRequest_SyncType) Enum() *SyncJobRequest_SyncType {
	p := new(SyncJobRequest_SyncType)
	*p = x
	return p
}

func (x SyncJobRequest_SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncJobRequest_SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enclave_proto_enumTypes[0].Descriptor()
}

func (SyncJobRequest_SyncType) Type() protoreflect.EnumType {
	return &file_api_proto_enclave_proto_enumTypes[0]
}

func (x SyncJobRequest_SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncJobRequest_SyncType.Descriptor instead.
func (SyncJobRequest_SyncType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{0, 0}
}

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_HEALTHY   HealthCheckResponse_Status = 0
	HealthCheckResponse_UNHEALTHY HealthCheckResponse_Status = 1
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "HEALTHY",
		1: "UNHEALTHY",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"HEALTHY":   0,
		"UNHEALTHY": 1,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enclave_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_api_proto_enclave_proto_enumTypes[1]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{12, 0}
}

// Request to process a synchronization job
// NOTE: Sync behavior is automatic based on exchange type:
// - IBKR: Auto-backfill from Flex (365 days) on first sync, then current day only
// - Crypto: Current snapshot only (DailySyncScheduler handles midnight UTC syncs)
type SyncJobRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserUid       string                  `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	Exchange      string                  `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                               // Optional, if not provided syncs all exchanges
	Type          SyncJobRequest_SyncType `protobuf:"varint,3,opt,name=type,proto3,enum=enclave.SyncJobRequest_SyncType" json:"type,omitempty"` // Deprecated, kept for backwards compatibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncJobRequest) Reset() {
	*x = SyncJobRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobRequest) ProtoMessage() {}

func (x *SyncJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobRequest.ProtoReflect.Descriptor instead.
func (*SyncJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{0}
}

func (x *SyncJobRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *SyncJobRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *SyncJobRequest) GetType() SyncJobRequest_SyncType {
	if x != nil {
		return x.Type
	}
	return SyncJobRequest_INCREMENTAL
}

// Response from processing a synchronization job
type SyncJobResponse struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Success            bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserUid            string                    `protobuf:"bytes,2,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	Exchange           string                    `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Synced             int32                     `protobuf:"varint,4,opt,name=synced,proto3" json:"synced,omitempty"`                                                   // Number of trades synced
	SnapshotsGenerated int32                     `protobuf:"varint,5,opt,name=snapshots_generated,json=snapshotsGenerated,proto3" json:"snapshots_generated,omitempty"` // Number of daily snapshots created
	LatestSnapshot     *SyncJobResponse_Snapshot `protobuf:"bytes,6,opt,name=latest_snapshot,json=latestSnapshot,proto3" json:"latest_snapshot,omitempty"`
	Error              string                    `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncJobResponse) Reset() {
	*x = SyncJobResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobResponse) ProtoMessage() {}

func (x *SyncJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobResponse.ProtoReflect.Descriptor instead.
func (*SyncJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{1}
}

func (x *SyncJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncJobResponse) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *SyncJobResponse) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *SyncJobResponse) GetSynced() int32 {
	if x != nil {
		return x.Synced
	}
	return 0
}

func (x *SyncJobResponse) GetSnapshotsGenerated() int32 {
	if x != nil {
		return x.SnapshotsGenerated
	}
	return 0
}

func (x *SyncJobResponse) GetLatestSnapshot() *SyncJobResponse_Snapshot {
	if x != nil {
		return x.LatestSnapshot
	}
	return nil
}

func (x *SyncJobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request for aggregated metrics
type AggregatedMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUid       string                 `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedMetricsRequest) Reset() {
	*x = AggregatedMetricsRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetricsRequest) ProtoMessage() {}

func (x *AggregatedMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetricsRequest.ProtoReflect.Descriptor instead.
func (*AggregatedMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{2}
}

func (x *AggregatedMetricsRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *AggregatedMetricsRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

// Response with aggregated metrics
type AggregatedMetricsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalBalance       float64                `protobuf:"fixed64,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	TotalEquity        float64                `protobuf:"fixed64,2,opt,name=total_equity,json=totalEquity,proto3" json:"total_equity,omitempty"`
	TotalRealizedPnl   float64                `protobuf:"fixed64,3,opt,name=total_realized_pnl,json=totalRealizedPnl,proto3" json:"total_realized_pnl,omitempty"`
	TotalUnrealizedPnl float64                `protobuf:"fixed64,4,opt,name=total_unrealized_pnl,json=totalUnrealizedPnl,proto3" json:"total_unrealized_pnl,omitempty"`
	TotalFees          float64                `protobuf:"fixed64,5,opt,name=total_fees,json=totalFees,proto3" json:"total_fees,omitempty"`
	TotalTrades        int32                  `protobuf:"varint,6,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	LastSync           int64                  `protobuf:"varint,7,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"` // Unix timestamp, nullable
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AggregatedMetricsResponse) Reset() {
	*x = AggregatedMetricsResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetricsResponse) ProtoMessage() {}

func (x *AggregatedMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetricsResponse.ProtoReflect.Descriptor instead.
func (*AggregatedMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{3}
}

func (x *AggregatedMetricsResponse) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetTotalEquity() float64 {
	if x != nil {
		return x.TotalEquity
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetTotalRealizedPnl() float64 {
	if x != nil {
		return x.TotalRealizedPnl
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetTotalUnrealizedPnl() float64 {
	if x != nil {
		return x.TotalUnrealizedPnl
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetTotalFees() float64 {
	if x != nil {
		return x.TotalFees
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetLastSync() int64 {
	if x != nil {
		return x.LastSync
	}
	return 0
}

// Request for snapshot time series
type SnapshotTimeSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUid       string                 `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                     // Optional
	StartDate     int64                  `protobuf:"varint,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Unix timestamp (milliseconds), optional
	EndDate       int64                  `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Unix timestamp (milliseconds), optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotTimeSeriesRequest) Reset() {
	*x = SnapshotTimeSeriesRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotTimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotTimeSeriesRequest) ProtoMessage() {}

func (x *SnapshotTimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotTimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*SnapshotTimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotTimeSeriesRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *SnapshotTimeSeriesRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *SnapshotTimeSeriesRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *SnapshotTimeSeriesRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

// Response with snapshot time series
type SnapshotTimeSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*DailySnapshot       `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotTimeSeriesResponse) Reset() {
	*x = SnapshotTimeSeriesResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotTimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotTimeSeriesResponse) ProtoMessage() {}

func (x *SnapshotTimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotTimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*SnapshotTimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotTimeSeriesResponse) GetSnapshots() []*DailySnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// Daily snapshot data point
type DailySnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserUid         string                 `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	Exchange        string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Timestamp       int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // Unix timestamp (milliseconds) - daily snapshot at 00:00 UTC
	TotalEquity     float64                `protobuf:"fixed64,4,opt,name=total_equity,json=totalEquity,proto3" json:"total_equity,omitempty"`             // Total account value (realized + unrealized)
	RealizedBalance float64                `protobuf:"fixed64,5,opt,name=realized_balance,json=realizedBalance,proto3" json:"realized_balance,omitempty"` // Available cash/balance
	UnrealizedPnl   float64                `protobuf:"fixed64,6,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`       // Unrealized P&L from open positions
	Deposits        float64                `protobuf:"fixed64,7,opt,name=deposits,proto3" json:"deposits,omitempty"`                                      // Cash deposited on this day
	Withdrawals     float64                `protobuf:"fixed64,8,opt,name=withdrawals,proto3" json:"withdrawals,omitempty"`                                // Cash withdrawn on this day
	Breakdown       *MarketBreakdown       `protobuf:"bytes,9,opt,name=breakdown,proto3" json:"breakdown,omitempty"`                                      // Market breakdown (spot/swap/options)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailySnapshot) Reset() {
	*x = DailySnapshot{}
	mi := &file_api_proto_enclave_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySnapshot) ProtoMessage() {}

func (x *DailySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySnapshot.ProtoReflect.Descriptor instead.
func (*DailySnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{6}
}

func (x *DailySnapshot) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *DailySnapshot) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *DailySnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DailySnapshot) GetTotalEquity() float64 {
	if x != nil {
		return x.TotalEquity
	}
	return 0
}

func (x *DailySnapshot) GetRealizedBalance() float64 {
	if x != nil {
		return x.RealizedBalance
	}
	return 0
}

func (x *DailySnapshot) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *DailySnapshot) GetDeposits() float64 {
	if x != nil {
		return x.Deposits
	}
	return 0
}

func (x *DailySnapshot) GetWithdrawals() float64 {
	if x != nil {
		return x.Withdrawals
	}
	return 0
}

func (x *DailySnapshot) GetBreakdown() *MarketBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

// Market breakdown for a snapshot
// Supports both crypto (spot/swap) and traditional (stocks/futures/cfd)
type MarketBreakdown struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Global *MarketMetrics         `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	// Crypto categories
	Spot *MarketMetrics `protobuf:"bytes,2,opt,name=spot,proto3" json:"spot,omitempty"`
	Swap *MarketMetrics `protobuf:"bytes,3,opt,name=swap,proto3" json:"swap,omitempty"`
	// Traditional categories (IBKR, etc.)
	Stocks      *MarketMetrics `protobuf:"bytes,5,opt,name=stocks,proto3" json:"stocks,omitempty"`
	Futures     *MarketMetrics `protobuf:"bytes,6,opt,name=futures,proto3" json:"futures,omitempty"`
	Cfd         *MarketMetrics `protobuf:"bytes,7,opt,name=cfd,proto3" json:"cfd,omitempty"`
	Forex       *MarketMetrics `protobuf:"bytes,8,opt,name=forex,proto3" json:"forex,omitempty"`
	Commodities *MarketMetrics `protobuf:"bytes,9,opt,name=commodities,proto3" json:"commodities,omitempty"`
	// Shared
	Options       *MarketMetrics `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketBreakdown) Reset() {
	*x = MarketBreakdown{}
	mi := &file_api_proto_enclave_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketBreakdown) ProtoMessage() {}

func (x *MarketBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketBreakdown.ProtoReflect.Descriptor instead.
func (*MarketBreakdown) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{7}
}

func (x *MarketBreakdown) GetGlobal() *MarketMetrics {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *MarketBreakdown) GetSpot() *MarketMetrics {
	if x != nil {
		return x.Spot
	}
	return nil
}

func (x *MarketBreakdown) GetSwap() *MarketMetrics {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *MarketBreakdown) GetStocks() *MarketMetrics {
	if x != nil {
		return x.Stocks
	}
	return nil
}

func (x *MarketBreakdown) GetFutures() *MarketMetrics {
	if x != nil {
		return x.Futures
	}
	return nil
}

func (x *MarketBreakdown) GetCfd() *MarketMetrics {
	if x != nil {
		return x.Cfd
	}
	return nil
}

func (x *MarketBreakdown) GetForex() *MarketMetrics {
	if x != nil {
		return x.Forex
	}
	return nil
}

func (x *MarketBreakdown) GetCommodities() *MarketMetrics {
	if x != nil {
		return x.Commodities
	}
	return nil
}

func (x *MarketBreakdown) GetOptions() *MarketMetrics {
	if x != nil {
		return x.Options
	}
	return nil
}

// Metrics per market type
type MarketMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Equity          float64                `protobuf:"fixed64,1,opt,name=equity,proto3" json:"equity,omitempty"`
	AvailableMargin float64                `protobuf:"fixed64,2,opt,name=available_margin,json=availableMargin,proto3" json:"available_margin,omitempty"`
	Volume          float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Trades          int32                  `protobuf:"varint,4,opt,name=trades,proto3" json:"trades,omitempty"` // Number of executed trades (not orders)
	TradingFees     float64                `protobuf:"fixed64,5,opt,name=trading_fees,json=tradingFees,proto3" json:"trading_fees,omitempty"`
	FundingFees     float64                `protobuf:"fixed64,6,opt,name=funding_fees,json=fundingFees,proto3" json:"funding_fees,omitempty"`  // Only for swap/perp markets
	LongTrades      int32                  `protobuf:"varint,7,opt,name=long_trades,json=longTrades,proto3" json:"long_trades,omitempty"`      // Number of buy trades
	ShortTrades     int32                  `protobuf:"varint,8,opt,name=short_trades,json=shortTrades,proto3" json:"short_trades,omitempty"`   // Number of sell trades
	LongVolume      float64                `protobuf:"fixed64,9,opt,name=long_volume,json=longVolume,proto3" json:"long_volume,omitempty"`     // USD volume of buy trades
	ShortVolume     float64                `protobuf:"fixed64,10,opt,name=short_volume,json=shortVolume,proto3" json:"short_volume,omitempty"` // USD volume of sell trades
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarketMetrics) Reset() {
	*x = MarketMetrics{}
	mi := &file_api_proto_enclave_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketMetrics) ProtoMessage() {}

func (x *MarketMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketMetrics.ProtoReflect.Descriptor instead.
func (*MarketMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{8}
}

func (x *MarketMetrics) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *MarketMetrics) GetAvailableMargin() float64 {
	if x != nil {
		return x.AvailableMargin
	}
	return 0
}

func (x *MarketMetrics) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MarketMetrics) GetTrades() int32 {
	if x != nil {
		return x.Trades
	}
	return 0
}

func (x *MarketMetrics) GetTradingFees() float64 {
	if x != nil {
		return x.TradingFees
	}
	return 0
}

func (x *MarketMetrics) GetFundingFees() float64 {
	if x != nil {
		return x.FundingFees
	}
	return 0
}

func (x *MarketMetrics) GetLongTrades() int32 {
	if x != nil {
		return x.LongTrades
	}
	return 0
}

func (x *MarketMetrics) GetShortTrades() int32 {
	if x != nil {
		return x.ShortTrades
	}
	return 0
}

func (x *MarketMetrics) GetLongVolume() float64 {
	if x != nil {
		return x.LongVolume
	}
	return 0
}

func (x *MarketMetrics) GetShortVolume() float64 {
	if x != nil {
		return x.ShortVolume
	}
	return 0
}

// Request to create a user with exchange connection
type CreateUserConnectionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserUid           string                 `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`                                  // User UID from Platform (required - ensures Platform/Enclave sync)
	Exchange          string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                                               // Exchange name (e.g., "binance", "coinbase")
	Label             string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`                                                     // User-friendly label (e.g., "Main Account")
	ApiKey            string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                                     // API key (will be encrypted)
	ApiSecret         string                 `protobuf:"bytes,5,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`                            // API secret (will be encrypted)
	Passphrase        string                 `protobuf:"bytes,6,opt,name=passphrase,proto3" json:"passphrase,omitempty"`                                           // Optional passphrase (will be encrypted)
	ExcludeFromReport bool                   `protobuf:"varint,7,opt,name=exclude_from_report,json=excludeFromReport,proto3" json:"exclude_from_report,omitempty"` // true = analytics only, excluded from certified report
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateUserConnectionRequest) Reset() {
	*x = CreateUserConnectionRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserConnectionRequest) ProtoMessage() {}

func (x *CreateUserConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserConnectionRequest.ProtoReflect.Descriptor instead.
func (*CreateUserConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserConnectionRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *CreateUserConnectionRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CreateUserConnectionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateUserConnectionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateUserConnectionRequest) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *CreateUserConnectionRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *CreateUserConnectionRequest) GetExcludeFromReport() bool {
	if x != nil {
		return x.ExcludeFromReport
	}
	return false
}

// Response from creating a user with exchange connection
type CreateUserConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserUid       string                 `protobuf:"bytes,2,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"` // Auto-generated UID for the user
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                    // Error message if success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserConnectionResponse) Reset() {
	*x = CreateUserConnectionResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserConnectionResponse) ProtoMessage() {}

func (x *CreateUserConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserConnectionResponse.ProtoReflect.Descriptor instead.
func (*CreateUserConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateUserConnectionResponse) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *CreateUserConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{11}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=enclave.HealthCheckResponse_Status" json:"status,omitempty"`
	Enclave       bool                       `protobuf:"varint,2,opt,name=enclave,proto3" json:"enclave,omitempty"`
	Version       string                     `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        float64                    `protobuf:"fixed64,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{12}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_HEALTHY
}

func (x *HealthCheckResponse) GetEnclave() bool {
	if x != nil {
		return x.Enclave
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() float64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

// Request for performance metrics
type PerformanceMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUid       string                 `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`                     // Optional - filter by exchange
	StartDate     int64                  `protobuf:"varint,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Unix timestamp (milliseconds), optional
	EndDate       int64                  `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Unix timestamp (milliseconds), optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceMetricsRequest) Reset() {
	*x = PerformanceMetricsRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetricsRequest) ProtoMessage() {}

func (x *PerformanceMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetricsRequest.ProtoReflect.Descriptor instead.
func (*PerformanceMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{13}
}

func (x *PerformanceMetricsRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *PerformanceMetricsRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PerformanceMetricsRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *PerformanceMetricsRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

// Response with performance metrics
type PerformanceMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Risk-adjusted returns
	SharpeRatio  float64 `protobuf:"fixed64,1,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	SortinoRatio float64 `protobuf:"fixed64,2,opt,name=sortino_ratio,json=sortinoRatio,proto3" json:"sortino_ratio,omitempty"`
	CalmarRatio  float64 `protobuf:"fixed64,3,opt,name=calmar_ratio,json=calmarRatio,proto3" json:"calmar_ratio,omitempty"`
	// Volatility metrics
	Volatility        float64 `protobuf:"fixed64,4,opt,name=volatility,proto3" json:"volatility,omitempty"` // Annualized
	DownsideDeviation float64 `protobuf:"fixed64,5,opt,name=downside_deviation,json=downsideDeviation,proto3" json:"downside_deviation,omitempty"`
	// Drawdown metrics
	MaxDrawdown         float64 `protobuf:"fixed64,6,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`                          // Percentage
	MaxDrawdownDuration int32   `protobuf:"varint,7,opt,name=max_drawdown_duration,json=maxDrawdownDuration,proto3" json:"max_drawdown_duration,omitempty"` // Days
	CurrentDrawdown     float64 `protobuf:"fixed64,8,opt,name=current_drawdown,json=currentDrawdown,proto3" json:"current_drawdown,omitempty"`
	// Win/Loss metrics
	WinRate      float64 `protobuf:"fixed64,9,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"` // Percentage
	ProfitFactor float64 `protobuf:"fixed64,10,opt,name=profit_factor,json=profitFactor,proto3" json:"profit_factor,omitempty"`
	AvgWin       float64 `protobuf:"fixed64,11,opt,name=avg_win,json=avgWin,proto3" json:"avg_win,omitempty"`
	AvgLoss      float64 `protobuf:"fixed64,12,opt,name=avg_loss,json=avgLoss,proto3" json:"avg_loss,omitempty"`
	// Period info
	PeriodStart int64 `protobuf:"varint,13,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"` // Unix timestamp
	PeriodEnd   int64 `protobuf:"varint,14,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`       // Unix timestamp
	DataPoints  int32 `protobuf:"varint,15,opt,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	// Error handling
	Success       bool   `protobuf:"varint,16,opt,name=success,proto3" json:"success,omitempty"`
	Error         string `protobuf:"bytes,17,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceMetricsResponse) Reset() {
	*x = PerformanceMetricsResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetricsResponse) ProtoMessage() {}

func (x *PerformanceMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetricsResponse.ProtoReflect.Descriptor instead.
func (*PerformanceMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{14}
}

func (x *PerformanceMetricsResponse) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetSortinoRatio() float64 {
	if x != nil {
		return x.SortinoRatio
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetCalmarRatio() float64 {
	if x != nil {
		return x.CalmarRatio
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetDownsideDeviation() float64 {
	if x != nil {
		return x.DownsideDeviation
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetMaxDrawdownDuration() int32 {
	if x != nil {
		return x.MaxDrawdownDuration
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetCurrentDrawdown() float64 {
	if x != nil {
		return x.CurrentDrawdown
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetProfitFactor() float64 {
	if x != nil {
		return x.ProfitFactor
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetAvgWin() float64 {
	if x != nil {
		return x.AvgWin
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetAvgLoss() float64 {
	if x != nil {
		return x.AvgLoss
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetPeriodStart() int64 {
	if x != nil {
		return x.PeriodStart
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetPeriodEnd() int64 {
	if x != nil {
		return x.PeriodEnd
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetDataPoints() int32 {
	if x != nil {
		return x.DataPoints
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PerformanceMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to generate a cryptographically signed report
type ReportRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserUid            string                 `protobuf:"bytes,1,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	StartDate          string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD (optional, defaults to first snapshot)
	EndDate            string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD (optional, defaults to last snapshot)
	Benchmark          string                 `protobuf:"bytes,4,opt,name=benchmark,proto3" json:"benchmark,omitempty"`                  // "SPY" | "BTC-USD" | "" (optional)
	IncludeRiskMetrics bool                   `protobuf:"varint,5,opt,name=include_risk_metrics,json=includeRiskMetrics,proto3" json:"include_risk_metrics,omitempty"`
	IncludeDrawdown    bool                   `protobuf:"varint,6,opt,name=include_drawdown,json=includeDrawdown,proto3" json:"include_drawdown,omitempty"`
	ReportName         string                 `protobuf:"bytes,7,opt,name=report_name,json=reportName,proto3" json:"report_name,omitempty"`
	BaseCurrency       string                 `protobuf:"bytes,8,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"` // USD, EUR, etc. (default: USD)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{15}
}

func (x *ReportRequest) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *ReportRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ReportRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ReportRequest) GetBenchmark() string {
	if x != nil {
		return x.Benchmark
	}
	return ""
}

func (x *ReportRequest) GetIncludeRiskMetrics() bool {
	if x != nil {
		return x.IncludeRiskMetrics
	}
	return false
}

func (x *ReportRequest) GetIncludeDrawdown() bool {
	if x != nil {
		return x.IncludeDrawdown
	}
	return false
}

func (x *ReportRequest) GetReportName() string {
	if x != nil {
		return x.ReportName
	}
	return ""
}

func (x *ReportRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

// Response with cryptographically signed report
type SignedReportResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Report metadata
	ReportId     string   `protobuf:"bytes,10,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	UserUid      string   `protobuf:"bytes,11,opt,name=user_uid,json=userUid,proto3" json:"user_uid,omitempty"`
	ReportName   string   `protobuf:"bytes,12,opt,name=report_name,json=reportName,proto3" json:"report_name,omitempty"`
	GeneratedAt  string   `protobuf:"bytes,13,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // ISO 8601
	PeriodStart  string   `protobuf:"bytes,14,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"` // ISO 8601
	PeriodEnd    string   `protobuf:"bytes,15,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`       // ISO 8601
	BaseCurrency string   `protobuf:"bytes,16,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	Benchmark    string   `protobuf:"bytes,17,opt,name=benchmark,proto3" json:"benchmark,omitempty"`
	DataPoints   int32    `protobuf:"varint,18,opt,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Exchanges    []string `protobuf:"bytes,19,rep,name=exchanges,proto3" json:"exchanges,omitempty"` // Connected exchanges (cryptographically signed)
	// Core metrics
	TotalReturn      float64 `protobuf:"fixed64,20,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"`
	AnnualizedReturn float64 `protobuf:"fixed64,21,opt,name=annualized_return,json=annualizedReturn,proto3" json:"annualized_return,omitempty"`
	Volatility       float64 `protobuf:"fixed64,22,opt,name=volatility,proto3" json:"volatility,omitempty"`
	SharpeRatio      float64 `protobuf:"fixed64,23,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	SortinoRatio     float64 `protobuf:"fixed64,24,opt,name=sortino_ratio,json=sortinoRatio,proto3" json:"sortino_ratio,omitempty"`
	MaxDrawdown      float64 `protobuf:"fixed64,25,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`
	CalmarRatio      float64 `protobuf:"fixed64,26,opt,name=calmar_ratio,json=calmarRatio,proto3" json:"calmar_ratio,omitempty"`
	// Risk metrics (optional, if include_risk_metrics=true)
	Var_95            float64 `protobuf:"fixed64,30,opt,name=var_95,json=var95,proto3" json:"var_95,omitempty"`
	Var_99            float64 `protobuf:"fixed64,31,opt,name=var_99,json=var99,proto3" json:"var_99,omitempty"`
	ExpectedShortfall float64 `protobuf:"fixed64,32,opt,name=expected_shortfall,json=expectedShortfall,proto3" json:"expected_shortfall,omitempty"`
	Skewness          float64 `protobuf:"fixed64,33,opt,name=skewness,proto3" json:"skewness,omitempty"`
	Kurtosis          float64 `protobuf:"fixed64,34,opt,name=kurtosis,proto3" json:"kurtosis,omitempty"`
	// Benchmark metrics (optional, if benchmark provided)
	Alpha            float64 `protobuf:"fixed64,40,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta             float64 `protobuf:"fixed64,41,opt,name=beta,proto3" json:"beta,omitempty"`
	InformationRatio float64 `protobuf:"fixed64,42,opt,name=information_ratio,json=informationRatio,proto3" json:"information_ratio,omitempty"`
	TrackingError    float64 `protobuf:"fixed64,43,opt,name=tracking_error,json=trackingError,proto3" json:"tracking_error,omitempty"`
	Correlation      float64 `protobuf:"fixed64,44,opt,name=correlation,proto3" json:"correlation,omitempty"`
	// Drawdown data (optional, if include_drawdown=true)
	MaxDrawdownDuration int32                 `protobuf:"varint,50,opt,name=max_drawdown_duration,json=maxDrawdownDuration,proto3" json:"max_drawdown_duration,omitempty"`
	CurrentDrawdown     float64               `protobuf:"fixed64,51,opt,name=current_drawdown,json=currentDrawdown,proto3" json:"current_drawdown,omitempty"`
	DrawdownPeriods     []*DrawdownPeriodData `protobuf:"bytes,52,rep,name=drawdown_periods,json=drawdownPeriods,proto3" json:"drawdown_periods,omitempty"`
	// Chart data
	DailyReturns   []*DailyReturnData   `protobuf:"bytes,60,rep,name=daily_returns,json=dailyReturns,proto3" json:"daily_returns,omitempty"`
	MonthlyReturns []*MonthlyReturnData `protobuf:"bytes,61,rep,name=monthly_returns,json=monthlyReturns,proto3" json:"monthly_returns,omitempty"`
	// Cryptographic signature
	Signature          string `protobuf:"bytes,70,opt,name=signature,proto3" json:"signature,omitempty"`                                             // Base64 encoded ECDSA signature
	PublicKey          string `protobuf:"bytes,71,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                            // Base64 encoded public key for verification
	SignatureAlgorithm string `protobuf:"bytes,72,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"` // e.g., "ECDSA-P256-SHA256"
	ReportHash         string `protobuf:"bytes,73,opt,name=report_hash,json=reportHash,proto3" json:"report_hash,omitempty"`                         // SHA-256 hash of report data
	// Exchange details with KYC
	ExchangeDetails []*ExchangeInfo `protobuf:"bytes,90,rep,name=exchange_details,json=exchangeDetails,proto3" json:"exchange_details,omitempty"`
	// Enclave attestation
	EnclaveVersion string `protobuf:"bytes,80,opt,name=enclave_version,json=enclaveVersion,proto3" json:"enclave_version,omitempty"`
	AttestationId  string `protobuf:"bytes,81,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"` // SEV-SNP attestation ID (if available)
	EnclaveMode    string `protobuf:"bytes,82,opt,name=enclave_mode,json=enclaveMode,proto3" json:"enclave_mode,omitempty"`       // "production" | "development"
	// SEV-SNP launch measurement (hex-encoded). This is the hash of the
	// enclave code as measured by AMD SEV-SNP at boot. Clients should
	// compare this value with the measurement published for the
	// corresponding GitHub release to prove the report was generated by
	// the audited source code. Empty string when the enclave runs in
	// non-SEV-SNP (dev) mode.
	Measurement   string `protobuf:"bytes,83,opt,name=measurement,proto3" json:"measurement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedReportResponse) Reset() {
	*x = SignedReportResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedReportResponse) ProtoMessage() {}

func (x *SignedReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedReportResponse.ProtoReflect.Descriptor instead.
func (*SignedReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{16}
}

func (x *SignedReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignedReportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SignedReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *SignedReportResponse) GetUserUid() string {
	if x != nil {
		return x.UserUid
	}
	return ""
}

func (x *SignedReportResponse) GetReportName() string {
	if x != nil {
		return x.ReportName
	}
	return ""
}

func (x *SignedReportResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *SignedReportResponse) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *SignedReportResponse) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *SignedReportResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *SignedReportResponse) GetBenchmark() string {
	if x != nil {
		return x.Benchmark
	}
	return ""
}

func (x *SignedReportResponse) GetDataPoints() int32 {
	if x != nil {
		return x.DataPoints
	}
	return 0
}

func (x *SignedReportResponse) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *SignedReportResponse) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *SignedReportResponse) GetAnnualizedReturn() float64 {
	if x != nil {
		return x.AnnualizedReturn
	}
	return 0
}

func (x *SignedReportResponse) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *SignedReportResponse) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *SignedReportResponse) GetSortinoRatio() float64 {
	if x != nil {
		return x.SortinoRatio
	}
	return 0
}

func (x *SignedReportResponse) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *SignedReportResponse) GetCalmarRatio() float64 {
	if x != nil {
		return x.CalmarRatio
	}
	return 0
}

func (x *SignedReportResponse) GetVar_95() float64 {
	if x != nil {
		return x.Var_95
	}
	return 0
}

func (x *SignedReportResponse) GetVar_99() float64 {
	if x != nil {
		return x.Var_99
	}
	return 0
}

func (x *SignedReportResponse) GetExpectedShortfall() float64 {
	if x != nil {
		return x.ExpectedShortfall
	}
	return 0
}

func (x *SignedReportResponse) GetSkewness() float64 {
	if x != nil {
		return x.Skewness
	}
	return 0
}

func (x *SignedReportResponse) GetKurtosis() float64 {
	if x != nil {
		return x.Kurtosis
	}
	return 0
}

func (x *SignedReportResponse) GetAlpha() float64 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *SignedReportResponse) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *SignedReportResponse) GetInformationRatio() float64 {
	if x != nil {
		return x.InformationRatio
	}
	return 0
}

func (x *SignedReportResponse) GetTrackingError() float64 {
	if x != nil {
		return x.TrackingError
	}
	return 0
}

func (x *SignedReportResponse) GetCorrelation() float64 {
	if x != nil {
		return x.Correlation
	}
	return 0
}

func (x *SignedReportResponse) GetMaxDrawdownDuration() int32 {
	if x != nil {
		return x.MaxDrawdownDuration
	}
	return 0
}

func (x *SignedReportResponse) GetCurrentDrawdown() float64 {
	if x != nil {
		return x.CurrentDrawdown
	}
	return 0
}

func (x *SignedReportResponse) GetDrawdownPeriods() []*DrawdownPeriodData {
	if x != nil {
		return x.DrawdownPeriods
	}
	return nil
}

func (x *SignedReportResponse) GetDailyReturns() []*DailyReturnData {
	if x != nil {
		return x.DailyReturns
	}
	return nil
}

func (x *SignedReportResponse) GetMonthlyReturns() []*MonthlyReturnData {
	if x != nil {
		return x.MonthlyReturns
	}
	return nil
}

func (x *SignedReportResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedReportResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SignedReportResponse) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *SignedReportResponse) GetReportHash() string {
	if x != nil {
		return x.ReportHash
	}
	return ""
}

func (x *SignedReportResponse) GetExchangeDetails() []*ExchangeInfo {
	if x != nil {
		return x.ExchangeDetails
	}
	return nil
}

func (x *SignedReportResponse) GetEnclaveVersion() string {
	if x != nil {
		return x.EnclaveVersion
	}
	return ""
}

func (x *SignedReportResponse) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

func (x *SignedReportResponse) GetEnclaveMode() string {
	if x != nil {
		return x.EnclaveMode
	}
	return ""
}

func (x *SignedReportResponse) GetMeasurement() string {
	if x != nil {
		return x.Measurement
	}
	return ""
}

// Exchange info with KYC and paper status
type ExchangeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KycLevel      string                 `protobuf:"bytes,2,opt,name=kyc_level,json=kycLevel,proto3" json:"kyc_level,omitempty"` // "none", "basic", "intermediate", "advanced", or "" (unsupported)
	IsPaper       bool                   `protobuf:"varint,3,opt,name=is_paper,json=isPaper,proto3" json:"is_paper,omitempty"`   // true = paper/testnet, false = live
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeInfo) Reset() {
	*x = ExchangeInfo{}
	mi := &file_api_proto_enclave_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeInfo) ProtoMessage() {}

func (x *ExchangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeInfo.ProtoReflect.Descriptor instead.
func (*ExchangeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{17}
}

func (x *ExchangeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExchangeInfo) GetKycLevel() string {
	if x != nil {
		return x.KycLevel
	}
	return ""
}

func (x *ExchangeInfo) GetIsPaper() bool {
	if x != nil {
		return x.IsPaper
	}
	return false
}

// Daily return data for charts
type DailyReturnData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Date             string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                                   // YYYY-MM-DD
	NetReturn        float64                `protobuf:"fixed64,2,opt,name=net_return,json=netReturn,proto3" json:"net_return,omitempty"`                      // Daily return in %
	BenchmarkReturn  float64                `protobuf:"fixed64,3,opt,name=benchmark_return,json=benchmarkReturn,proto3" json:"benchmark_return,omitempty"`    // Benchmark return in %
	Outperformance   float64                `protobuf:"fixed64,4,opt,name=outperformance,proto3" json:"outperformance,omitempty"`                             // Portfolio - Benchmark
	CumulativeReturn float64                `protobuf:"fixed64,5,opt,name=cumulative_return,json=cumulativeReturn,proto3" json:"cumulative_return,omitempty"` // Cumulative return factor
	Nav              float64                `protobuf:"fixed64,6,opt,name=nav,proto3" json:"nav,omitempty"`                                                   // Net Asset Value
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DailyReturnData) Reset() {
	*x = DailyReturnData{}
	mi := &file_api_proto_enclave_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReturnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReturnData) ProtoMessage() {}

func (x *DailyReturnData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReturnData.ProtoReflect.Descriptor instead.
func (*DailyReturnData) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{18}
}

func (x *DailyReturnData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyReturnData) GetNetReturn() float64 {
	if x != nil {
		return x.NetReturn
	}
	return 0
}

func (x *DailyReturnData) GetBenchmarkReturn() float64 {
	if x != nil {
		return x.BenchmarkReturn
	}
	return 0
}

func (x *DailyReturnData) GetOutperformance() float64 {
	if x != nil {
		return x.Outperformance
	}
	return 0
}

func (x *DailyReturnData) GetCumulativeReturn() float64 {
	if x != nil {
		return x.CumulativeReturn
	}
	return 0
}

func (x *DailyReturnData) GetNav() float64 {
	if x != nil {
		return x.Nav
	}
	return 0
}

// Monthly return data for tables
type MonthlyReturnData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                                // YYYY-MM
	NetReturn       float64                `protobuf:"fixed64,2,opt,name=net_return,json=netReturn,proto3" json:"net_return,omitempty"`                   // Monthly return in %
	BenchmarkReturn float64                `protobuf:"fixed64,3,opt,name=benchmark_return,json=benchmarkReturn,proto3" json:"benchmark_return,omitempty"` // Benchmark return in %
	Outperformance  float64                `protobuf:"fixed64,4,opt,name=outperformance,proto3" json:"outperformance,omitempty"`                          // Portfolio - Benchmark
	Aum             float64                `protobuf:"fixed64,5,opt,name=aum,proto3" json:"aum,omitempty"`                                                // Assets Under Management
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MonthlyReturnData) Reset() {
	*x = MonthlyReturnData{}
	mi := &file_api_proto_enclave_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyReturnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyReturnData) ProtoMessage() {}

func (x *MonthlyReturnData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyReturnData.ProtoReflect.Descriptor instead.
func (*MonthlyReturnData) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{19}
}

func (x *MonthlyReturnData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MonthlyReturnData) GetNetReturn() float64 {
	if x != nil {
		return x.NetReturn
	}
	return 0
}

func (x *MonthlyReturnData) GetBenchmarkReturn() float64 {
	if x != nil {
		return x.BenchmarkReturn
	}
	return 0
}

func (x *MonthlyReturnData) GetOutperformance() float64 {
	if x != nil {
		return x.Outperformance
	}
	return 0
}

func (x *MonthlyReturnData) GetAum() float64 {
	if x != nil {
		return x.Aum
	}
	return 0
}

// Drawdown period data
type DrawdownPeriodData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Depth         float64                `protobuf:"fixed64,3,opt,name=depth,proto3" json:"depth,omitempty"`      // Max drawdown during period (%)
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // Days
	Recovered     bool                   `protobuf:"varint,5,opt,name=recovered,proto3" json:"recovered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawdownPeriodData) Reset() {
	*x = DrawdownPeriodData{}
	mi := &file_api_proto_enclave_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawdownPeriodData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawdownPeriodData) ProtoMessage() {}

func (x *DrawdownPeriodData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawdownPeriodData.ProtoReflect.Descriptor instead.
func (*DrawdownPeriodData) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{20}
}

func (x *DrawdownPeriodData) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DrawdownPeriodData) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *DrawdownPeriodData) GetDepth() float64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *DrawdownPeriodData) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *DrawdownPeriodData) GetRecovered() bool {
	if x != nil {
		return x.Recovered
	}
	return false
}

// Request to verify a report signature
type VerifySignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportHash    string                 `protobuf:"bytes,1,opt,name=report_hash,json=reportHash,proto3" json:"report_hash,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureRequest) Reset() {
	*x = VerifySignatureRequest{}
	mi := &file_api_proto_enclave_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureRequest) ProtoMessage() {}

func (x *VerifySignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureRequest.ProtoReflect.Descriptor instead.
func (*VerifySignatureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{21}
}

func (x *VerifySignatureRequest) GetReportHash() string {
	if x != nil {
		return x.ReportHash
	}
	return ""
}

func (x *VerifySignatureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifySignatureRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Response from signature verification
type VerifySignatureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySignatureResponse) Reset() {
	*x = VerifySignatureResponse{}
	mi := &file_api_proto_enclave_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySignatureResponse) ProtoMessage() {}

func (x *VerifySignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySignatureResponse.ProtoReflect.Descriptor instead.
func (*VerifySignatureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{22}
}

func (x *VerifySignatureResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifySignatureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SyncJobResponse_Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Equity        float64                `protobuf:"fixed64,2,opt,name=equity,proto3" json:"equity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncJobResponse_Snapshot) Reset() {
	*x = SyncJobResponse_Snapshot{}
	mi := &file_api_proto_enclave_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncJobResponse_Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncJobResponse_Snapshot) ProtoMessage() {}

func (x *SyncJobResponse_Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_enclave_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncJobResponse_Snapshot.ProtoReflect.Descriptor instead.
func (*SyncJobResponse_Snapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_enclave_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SyncJobResponse_Snapshot) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *SyncJobResponse_Snapshot) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *SyncJobResponse_Snapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_enclave_proto protoreflect.FileDescriptor

const file_api_proto_enclave_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/enclave.proto\x12\aenclave\"\xb4\x01\n" +
	"\x0eSyncJobRequest\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .enclave.SyncJobRequest.SyncTypeR\x04type\"5\n" +
	"\bSyncType\x12\x0f\n" +
	"\vINCREMENTAL\x10\x00\x12\x0e\n" +
	"\n" +
	"HISTORICAL\x10\x01\x12\b\n" +
	"\x04FULL\x10\x02\"\xe9\x02\n" +
	"\x0fSyncJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\buser_uid\x18\x02 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x16\n" +
	"\x06synced\x18\x04 \x01(\x05R\x06synced\x12/\n" +
	"\x13snapshots_generated\x18\x05 \x01(\x05R\x12snapshotsGenerated\x12J\n" +
	"\x0flatest_snapshot\x18\x06 \x01(\v2!.enclave.SyncJobResponse.SnapshotR\x0elatestSnapshot\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x1aZ\n" +
	"\bSnapshot\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x16\n" +
	"\x06equity\x18\x02 \x01(\x01R\x06equity\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"Q\n" +
	"\x18AggregatedMetricsRequest\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\"\xa2\x02\n" +
	"\x19AggregatedMetricsResponse\x12#\n" +
	"\rtotal_balance\x18\x01 \x01(\x01R\ftotalBalance\x12!\n" +
	"\ftotal_equity\x18\x02 \x01(\x01R\vtotalEquity\x12,\n" +
	"\x12total_realized_pnl\x18\x03 \x01(\x01R\x10totalRealizedPnl\x120\n" +
	"\x14total_unrealized_pnl\x18\x04 \x01(\x01R\x12totalUnrealizedPnl\x12\x1d\n" +
	"\n" +
	"total_fees\x18\x05 \x01(\x01R\ttotalFees\x12!\n" +
	"\ftotal_trades\x18\x06 \x01(\x05R\vtotalTrades\x12\x1b\n" +
	"\tlast_sync\x18\a \x01(\x03R\blastSync\"\x8c\x01\n" +
	"\x19SnapshotTimeSeriesRequest\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\x03R\aendDate\"R\n" +
	"\x1aSnapshotTimeSeriesResponse\x124\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x16.enclave.DailySnapshotR\tsnapshots\"\xcf\x02\n" +
	"\rDailySnapshot\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12!\n" +
	"\ftotal_equity\x18\x04 \x01(\x01R\vtotalEquity\x12)\n" +
	"\x10realized_balance\x18\x05 \x01(\x01R\x0frealizedBalance\x12%\n" +
	"\x0eunrealized_pnl\x18\x06 \x01(\x01R\runrealizedPnl\x12\x1a\n" +
	"\bdeposits\x18\a \x01(\x01R\bdeposits\x12 \n" +
	"\vwithdrawals\x18\b \x01(\x01R\vwithdrawals\x126\n" +
	"\tbreakdown\x18\t \x01(\v2\x18.enclave.MarketBreakdownR\tbreakdown\"\xbf\x03\n" +
	"\x0fMarketBreakdown\x12.\n" +
	"\x06global\x18\x01 \x01(\v2\x16.enclave.MarketMetricsR\x06global\x12*\n" +
	"\x04spot\x18\x02 \x01(\v2\x16.enclave.MarketMetricsR\x04spot\x12*\n" +
	"\x04swap\x18\x03 \x01(\v2\x16.enclave.MarketMetricsR\x04swap\x12.\n" +
	"\x06stocks\x18\x05 \x01(\v2\x16.enclave.MarketMetricsR\x06stocks\x120\n" +
	"\afutures\x18\x06 \x01(\v2\x16.enclave.MarketMetricsR\afutures\x12(\n" +
	"\x03cfd\x18\a \x01(\v2\x16.enclave.MarketMetricsR\x03cfd\x12,\n" +
	"\x05forex\x18\b \x01(\v2\x16.enclave.MarketMetricsR\x05forex\x128\n" +
	"\vcommodities\x18\t \x01(\v2\x16.enclave.MarketMetricsR\vcommodities\x120\n" +
	"\aoptions\x18\x04 \x01(\v2\x16.enclave.MarketMetricsR\aoptions\"\xd0\x02\n" +
	"\rMarketMetrics\x12\x16\n" +
	"\x06equity\x18\x01 \x01(\x01R\x06equity\x12)\n" +
	"\x10available_margin\x18\x02 \x01(\x01R\x0favailableMargin\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x16\n" +
	"\x06trades\x18\x04 \x01(\x05R\x06trades\x12!\n" +
	"\ftrading_fees\x18\x05 \x01(\x01R\vtradingFees\x12!\n" +
	"\ffunding_fees\x18\x06 \x01(\x01R\vfundingFees\x12\x1f\n" +
	"\vlong_trades\x18\a \x01(\x05R\n" +
	"longTrades\x12!\n" +
	"\fshort_trades\x18\b \x01(\x05R\vshortTrades\x12\x1f\n" +
	"\vlong_volume\x18\t \x01(\x01R\n" +
	"longVolume\x12!\n" +
	"\fshort_volume\x18\n" +
	" \x01(\x01R\vshortVolume\"\xf2\x01\n" +
	"\x1bCreateUserConnectionRequest\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\x05 \x01(\tR\tapiSecret\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x06 \x01(\tR\n" +
	"passphrase\x12.\n" +
	"\x13exclude_from_report\x18\a \x01(\bR\x11excludeFromReport\"i\n" +
	"\x1cCreateUserConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\buser_uid\x18\x02 \x01(\tR\auserUid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"\xc4\x01\n" +
	"\x13HealthCheckResponse\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.enclave.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\aenclave\x18\x02 \x01(\bR\aenclave\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x01R\x06uptime\"$\n" +
	"\x06Status\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\r\n" +
	"\tUNHEALTHY\x10\x01\"\x8c\x01\n" +
	"\x19PerformanceMetricsRequest\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\x03R\aendDate\"\xdf\x04\n" +
	"\x1aPerformanceMetricsResponse\x12!\n" +
	"\fsharpe_ratio\x18\x01 \x01(\x01R\vsharpeRatio\x12#\n" +
	"\rsortino_ratio\x18\x02 \x01(\x01R\fsortinoRatio\x12!\n" +
	"\fcalmar_ratio\x18\x03 \x01(\x01R\vcalmarRatio\x12\x1e\n" +
	"\n" +
	"volatility\x18\x04 \x01(\x01R\n" +
	"volatility\x12-\n" +
	"\x12downside_deviation\x18\x05 \x01(\x01R\x11downsideDeviation\x12!\n" +
	"\fmax_drawdown\x18\x06 \x01(\x01R\vmaxDrawdown\x122\n" +
	"\x15max_drawdown_duration\x18\a \x01(\x05R\x13maxDrawdownDuration\x12)\n" +
	"\x10current_drawdown\x18\b \x01(\x01R\x0fcurrentDrawdown\x12\x19\n" +
	"\bwin_rate\x18\t \x01(\x01R\awinRate\x12#\n" +
	"\rprofit_factor\x18\n" +
	" \x01(\x01R\fprofitFactor\x12\x17\n" +
	"\aavg_win\x18\v \x01(\x01R\x06avgWin\x12\x19\n" +
	"\bavg_loss\x18\f \x01(\x01R\aavgLoss\x12!\n" +
	"\fperiod_start\x18\r \x01(\x03R\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x0e \x01(\x03R\tperiodEnd\x12\x1f\n" +
	"\vdata_points\x18\x0f \x01(\x05R\n" +
	"dataPoints\x12\x18\n" +
	"\asuccess\x18\x10 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x11 \x01(\tR\x05error\"\xa5\x02\n" +
	"\rReportRequest\x12\x19\n" +
	"\buser_uid\x18\x01 \x01(\tR\auserUid\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\x1c\n" +
	"\tbenchmark\x18\x04 \x01(\tR\tbenchmark\x120\n" +
	"\x14include_risk_metrics\x18\x05 \x01(\bR\x12includeRiskMetrics\x12)\n" +
	"\x10include_drawdown\x18\x06 \x01(\bR\x0fincludeDrawdown\x12\x1f\n" +
	"\vreport_name\x18\a \x01(\tR\n" +
	"reportName\x12#\n" +
	"\rbase_currency\x18\b \x01(\tR\fbaseCurrency\"\xca\f\n" +
	"\x14SignedReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\treport_id\x18\n" +
	" \x01(\tR\breportId\x12\x19\n" +
	"\buser_uid\x18\v \x01(\tR\auserUid\x12\x1f\n" +
	"\vreport_name\x18\f \x01(\tR\n" +
	"reportName\x12!\n" +
	"\fgenerated_at\x18\r \x01(\tR\vgeneratedAt\x12!\n" +
	"\fperiod_start\x18\x0e \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x0f \x01(\tR\tperiodEnd\x12#\n" +
	"\rbase_currency\x18\x10 \x01(\tR\fbaseCurrency\x12\x1c\n" +
	"\tbenchmark\x18\x11 \x01(\tR\tbenchmark\x12\x1f\n" +
	"\vdata_points\x18\x12 \x01(\x05R\n" +
	"dataPoints\x12\x1c\n" +
	"\texchanges\x18\x13 \x03(\tR\texchanges\x12!\n" +
	"\ftotal_return\x18\x14 \x01(\x01R\vtotalReturn\x12+\n" +
	"\x11annualized_return\x18\x15 \x01(\x01R\x10annualizedReturn\x12\x1e\n" +
	"\n" +
	"volatility\x18\x16 \x01(\x01R\n" +
	"volatility\x12!\n" +
	"\fsharpe_ratio\x18\x17 \x01(\x01R\vsharpeRatio\x12#\n" +
	"\rsortino_ratio\x18\x18 \x01(\x01R\fsortinoRatio\x12!\n" +
	"\fmax_drawdown\x18\x19 \x01(\x01R\vmaxDrawdown\x12!\n" +
	"\fcalmar_ratio\x18\x1a \x01(\x01R\vcalmarRatio\x12\x15\n" +
	"\x06var_95\x18\x1e \x01(\x01R\x05var95\x12\x15\n" +
	"\x06var_99\x18\x1f \x01(\x01R\x05var99\x12-\n" +
	"\x12expected_shortfall\x18  \x01(\x01R\x11expectedShortfall\x12\x1a\n" +
	"\bskewness\x18! \x01(\x01R\bskewness\x12\x1a\n" +
	"\bkurtosis\x18\" \x01(\x01R\bkurtosis\x12\x14\n" +
	"\x05alpha\x18( \x01(\x01R\x05alpha\x12\x12\n" +
	"\x04beta\x18) \x01(\x01R\x04beta\x12+\n" +
	"\x11information_ratio\x18* \x01(\x01R\x10informationRatio\x12%\n" +
	"\x0etracking_error\x18+ \x01(\x01R\rtrackingError\x12 \n" +
	"\vcorrelation\x18, \x01(\x01R\vcorrelation\x122\n" +
	"\x15max_drawdown_duration\x182 \x01(\x05R\x13maxDrawdownDuration\x12)\n" +
	"\x10current_drawdown\x183 \x01(\x01R\x0fcurrentDrawdown\x12F\n" +
	"\x10drawdown_periods\x184 \x03(\v2\x1b.enclave.DrawdownPeriodDataR\x0fdrawdownPeriods\x12=\n" +
	"\rdaily_returns\x18< \x03(\v2\x18.enclave.DailyReturnDataR\fdailyReturns\x12C\n" +
	"\x0fmonthly_returns\x18= \x03(\v2\x1a.enclave.MonthlyReturnDataR\x0emonthlyReturns\x12\x1c\n" +
	"\tsignature\x18F \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18G \x01(\tR\tpublicKey\x12/\n" +
	"\x13signature_algorithm\x18H \x01(\tR\x12signatureAlgorithm\x12\x1f\n" +
	"\vreport_hash\x18I \x01(\tR\n" +
	"reportHash\x12@\n" +
	"\x10exchange_details\x18Z \x03(\v2\x15.enclave.ExchangeInfoR\x0fexchangeDetails\x12'\n" +
	"\x0fenclave_version\x18P \x01(\tR\x0eenclaveVersion\x12%\n" +
	"\x0eattestation_id\x18Q \x01(\tR\rattestationId\x12!\n" +
	"\fenclave_mode\x18R \x01(\tR\venclaveMode\x12 \n" +
	"\vmeasurement\x18S \x01(\tR\vmeasurement\"Z\n" +
	"\fExchangeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tkyc_level\x18\x02 \x01(\tR\bkycLevel\x12\x19\n" +
	"\bis_paper\x18\x03 \x01(\bR\aisPaper\"\xd6\x01\n" +
	"\x0fDailyReturnData\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"net_return\x18\x02 \x01(\x01R\tnetReturn\x12)\n" +
	"\x10benchmark_return\x18\x03 \x01(\x01R\x0fbenchmarkReturn\x12&\n" +
	"\x0eoutperformance\x18\x04 \x01(\x01R\x0eoutperformance\x12+\n" +
	"\x11cumulative_return\x18\x05 \x01(\x01R\x10cumulativeReturn\x12\x10\n" +
	"\x03nav\x18\x06 \x01(\x01R\x03nav\"\xab\x01\n" +
	"\x11MonthlyReturnData\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"net_return\x18\x02 \x01(\x01R\tnetReturn\x12)\n" +
	"\x10benchmark_return\x18\x03 \x01(\x01R\x0fbenchmarkReturn\x12&\n" +
	"\x0eoutperformance\x18\x04 \x01(\x01R\x0eoutperformance\x12\x10\n" +
	"\x03aum\x18\x05 \x01(\x01R\x03aum\"\x9e\x01\n" +
	"\x12DrawdownPeriodData\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x01R\x05depth\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1c\n" +
	"\trecovered\x18\x05 \x01(\bR\trecovered\"v\n" +
	"\x16VerifySignatureRequest\x12\x1f\n" +
	"\vreport_hash\x18\x01 \x01(\tR\n" +
	"reportHash\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"E\n" +
	"\x17VerifySignatureResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xd2\x05\n" +
	"\x0eEnclaveService\x12C\n" +
	"\x0eProcessSyncJob\x12\x17.enclave.SyncJobRequest\x1a\x18.enclave.SyncJobResponse\x12]\n" +
	"\x14GetAggregatedMetrics\x12!.enclave.AggregatedMetricsRequest\x1a\".enclave.AggregatedMetricsResponse\x12`\n" +
	"\x15GetSnapshotTimeSeries\x12\".enclave.SnapshotTimeSeriesRequest\x1a#.enclave.SnapshotTimeSeriesResponse\x12c\n" +
	"\x14CreateUserConnection\x12$.enclave.CreateUserConnectionRequest\x1a%.enclave.CreateUserConnectionResponse\x12`\n" +
	"\x15GetPerformanceMetrics\x12\".enclave.PerformanceMetricsRequest\x1a#.enclave.PerformanceMetricsResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.enclave.HealthCheckRequest\x1a\x1c.enclave.HealthCheckResponse\x12M\n" +
	"\x14GenerateSignedReport\x12\x16.enclave.ReportRequest\x1a\x1d.enclave.SignedReportResponse\x12Z\n" +
	"\x15VerifyReportSignature\x12\x1f.enclave.VerifySignatureRequest\x1a .enclave.VerifySignatureResponseB*Z(github.com/trackrecord/enclave/api/protob\x06proto3"

var (
	file_api_proto_enclave_proto_rawDescOnce sync.Once
	file_api_proto_enclave_proto_rawDescData []byte
)

func file_api_proto_enclave_proto_rawDescGZIP() []byte {
	file_api_proto_enclave_proto_rawDescOnce.Do(func() {
		file_api_proto_enclave_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_enclave_proto_rawDesc), len(file_api_proto_enclave_proto_rawDesc)))
	})
	return file_api_proto_enclave_proto_rawDescData
}

var file_api_proto_enclave_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_enclave_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_enclave_proto_goTypes = []any{
	(SyncJobRequest_SyncType)(0),         // 0: enclave.SyncJobRequest.SyncType
	(HealthCheckResponse_Status)(0),      // 1: enclave.HealthCheckResponse.Status
	(*SyncJobRequest)(nil),               // 2: enclave.SyncJobRequest
	(*SyncJobResponse)(nil),              // 3: enclave.SyncJobResponse
	(*AggregatedMetricsRequest)(nil),     // 4: enclave.AggregatedMetricsRequest
	(*AggregatedMetricsResponse)(nil),    // 5: enclave.AggregatedMetricsResponse
	(*SnapshotTimeSeriesRequest)(nil),    // 6: enclave.SnapshotTimeSeriesRequest
	(*SnapshotTimeSeriesResponse)(nil),   // 7: enclave.SnapshotTimeSeriesResponse
	(*DailySnapshot)(nil),                // 8: enclave.DailySnapshot
	(*MarketBreakdown)(nil),              // 9: enclave.MarketBreakdown
	(*MarketMetrics)(nil),                // 10: enclave.MarketMetrics
	(*CreateUserConnectionRequest)(nil),  // 11: enclave.CreateUserConnectionRequest
	(*CreateUserConnectionResponse)(nil), // 12: enclave.CreateUserConnectionResponse
	(*HealthCheckRequest)(nil),           // 13: enclave.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 14: enclave.HealthCheckResponse
	(*PerformanceMetricsRequest)(nil),    // 15: enclave.PerformanceMetricsRequest
	(*PerformanceMetricsResponse)(nil),   // 16: enclave.PerformanceMetricsResponse
	(*ReportRequest)(nil),                // 17: enclave.ReportRequest
	(*SignedReportResponse)(nil),         // 18: enclave.SignedReportResponse
	(*ExchangeInfo)(nil),                 // 19: enclave.ExchangeInfo
	(*DailyReturnData)(nil),              // 20: enclave.DailyReturnData
	(*MonthlyReturnData)(nil),            // 21: enclave.MonthlyReturnData
	(*DrawdownPeriodData)(nil),           // 22: enclave.DrawdownPeriodData
	(*VerifySignatureRequest)(nil),       // 23: enclave.VerifySignatureRequest
	(*VerifySignatureResponse)(nil),      // 24: enclave.VerifySignatureResponse
	(*SyncJobResponse_Snapshot)(nil),     // 25: enclave.SyncJobResponse.Snapshot
}
var file_api_proto_enclave_proto_depIdxs = []int32{
	0,  // 0: enclave.SyncJobRequest.type:type_name -> enclave.SyncJobRequest.SyncType
	25, // 1: enclave.SyncJobResponse.latest_snapshot:type_name -> enclave.SyncJobResponse.Snapshot
	8,  // 2: enclave.SnapshotTimeSeriesResponse.snapshots:type_name -> enclave.DailySnapshot
	9,  // 3: enclave.DailySnapshot.breakdown:type_name -> enclave.MarketBreakdown
	10, // 4: enclave.MarketBreakdown.global:type_name -> enclave.MarketMetrics
	10, // 5: enclave.MarketBreakdown.spot:type_name -> enclave.MarketMetrics
	10, // 6: enclave.MarketBreakdown.swap:type_name -> enclave.MarketMetrics
	10, // 7: enclave.MarketBreakdown.stocks:type_name -> enclave.MarketMetrics
	10, // 8: enclave.MarketBreakdown.futures:type_name -> enclave.MarketMetrics
	10, // 9: enclave.MarketBreakdown.cfd:type_name -> enclave.MarketMetrics
	10, // 10: enclave.MarketBreakdown.forex:type_name -> enclave.MarketMetrics
	10, // 11: enclave.MarketBreakdown.commodities:type_name -> enclave.MarketMetrics
	10, // 12: enclave.MarketBreakdown.options:type_name -> enclave.MarketMetrics
	1,  // 13: enclave.HealthCheckResponse.status:type_name -> enclave.HealthCheckResponse.Status
	22, // 14: enclave.SignedReportResponse.drawdown_periods:type_name -> enclave.DrawdownPeriodData
	20, // 15: enclave.SignedReportResponse.daily_returns:type_name -> enclave.DailyReturnData
	21, // 16: enclave.SignedReportResponse.monthly_returns:type_name -> enclave.MonthlyReturnData
	19, // 17: enclave.SignedReportResponse.exchange_details:type_name -> enclave.ExchangeInfo
	2,  // 18: enclave.EnclaveService.ProcessSyncJob:input_type -> enclave.SyncJobRequest
	4,  // 19: enclave.EnclaveService.GetAggregatedMetrics:input_type -> enclave.AggregatedMetricsRequest
	6,  // 20: enclave.EnclaveService.GetSnapshotTimeSeries:input_type -> enclave.SnapshotTimeSeriesRequest
	11, // 21: enclave.EnclaveService.CreateUserConnection:input_type -> enclave.CreateUserConnectionRequest
	15, // 22: enclave.EnclaveService.GetPerformanceMetrics:input_type -> enclave.PerformanceMetricsRequest
	13, // 23: enclave.EnclaveService.HealthCheck:input_type -> enclave.HealthCheckRequest
	17, // 24: enclave.EnclaveService.GenerateSignedReport:input_type -> enclave.ReportRequest
	23, // 25: enclave.EnclaveService.VerifyReportSignature:input_type -> enclave.VerifySignatureRequest
	3,  // 26: enclave.EnclaveService.ProcessSyncJob:output_type -> enclave.SyncJobResponse
	5,  // 27: enclave.EnclaveService.GetAggregatedMetrics:output_type -> enclave.AggregatedMetricsResponse
	7,  // 28: enclave.EnclaveService.GetSnapshotTimeSeries:output_type -> enclave.SnapshotTimeSeriesResponse
	12, // 29: enclave.EnclaveService.CreateUserConnection:output_type -> enclave.CreateUserConnectionResponse
	16, // 30: enclave.EnclaveService.GetPerformanceMetrics:output_type -> enclave.PerformanceMetricsResponse
	14, // 31: enclave.EnclaveService.HealthCheck:output_type -> enclave.HealthCheckResponse
	18, // 32: enclave.EnclaveService.GenerateSignedReport:output_type -> enclave.SignedReportResponse
	24, // 33: enclave.EnclaveService.VerifyReportSignature:output_type -> enclave.VerifySignatureResponse
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_enclave_proto_init() }
func file_api_proto_enclave_proto_init() {
	if File_api_proto_enclave_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_enclave_proto_rawDesc), len(file_api_proto_enclave_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_enclave_proto_goTypes,
		DependencyIndexes: file_api_proto_enclave_proto_depIdxs,
		EnumInfos:         file_api_proto_enclave_proto_enumTypes,
		MessageInfos:      file_api_proto_enclave_proto_msgTypes,
	}.Build()
	File_api_proto_enclave_proto = out.File
	file_api_proto_enclave_proto_goTypes = nil
	file_api_proto_enclave_proto_depIdxs = nil
}
