// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/proto/enclave.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnclaveService_ProcessSyncJob_FullMethodName        = "/enclave.EnclaveService/ProcessSyncJob"
	EnclaveService_GetAggregatedMetrics_FullMethodName  = "/enclave.EnclaveService/GetAggregatedMetrics"
	EnclaveService_GetSnapshotTimeSeries_FullMethodName = "/enclave.EnclaveService/GetSnapshotTimeSeries"
	EnclaveService_CreateUserConnection_FullMethodName  = "/enclave.EnclaveService/CreateUserConnection"
	EnclaveService_GetPerformanceMetrics_FullMethodName = "/enclave.EnclaveService/GetPerformanceMetrics"
	EnclaveService_HealthCheck_FullMethodName           = "/enclave.EnclaveService/HealthCheck"
	EnclaveService_GenerateSignedReport_FullMethodName  = "/enclave.EnclaveService/GenerateSignedReport"
	EnclaveService_VerifyReportSignature_FullMethodName = "/enclave.EnclaveService/VerifyReportSignature"
)

// EnclaveServiceClient is the client API for EnclaveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Enclave service provides secure operations for trade synchronization
// and data aggregation. All operations return only aggregated, safe data.
type EnclaveServiceClient interface {
	// Process a synchronization job for a user's exchanges
	ProcessSyncJob(ctx context.Context, in *SyncJobRequest, opts ...grpc.CallOption) (*SyncJobResponse, error)
	// Get aggregated metrics for a user
	GetAggregatedMetrics(ctx context.Context, in *AggregatedMetricsRequest, opts ...grpc.CallOption) (*AggregatedMetricsResponse, error)
	// Get snapshot time series (daily snapshots history)
	GetSnapshotTimeSeries(ctx context.Context, in *SnapshotTimeSeriesRequest, opts ...grpc.CallOption) (*SnapshotTimeSeriesResponse, error)
	// Create a user with exchange connection (auto-generates UID)
	CreateUserConnection(ctx context.Context, in *CreateUserConnectionRequest, opts ...grpc.CallOption) (*CreateUserConnectionResponse, error)
	// Get performance metrics (Sharpe, volatility, drawdown, etc.)
	GetPerformanceMetrics(ctx context.Context, in *PerformanceMetricsRequest, opts ...grpc.CallOption) (*PerformanceMetricsResponse, error)
	// Health check for the enclave
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Generate a cryptographically signed report
	GenerateSignedReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*SignedReportResponse, error)
	// Verify a report signature
	VerifyReportSignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error)
}

type enclaveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnclaveServiceClient(cc grpc.ClientConnInterface) EnclaveServiceClient {
	return &enclaveServiceClient{cc}
}

func (c *enclaveServiceClient) ProcessSyncJob(ctx context.Context, in *SyncJobRequest, opts ...grpc.CallOption) (*SyncJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncJobResponse)
	err := c.cc.Invoke(ctx, EnclaveService_ProcessSyncJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) GetAggregatedMetrics(ctx context.Context, in *AggregatedMetricsRequest, opts ...grpc.CallOption) (*AggregatedMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregatedMetricsResponse)
	err := c.cc.Invoke(ctx, EnclaveService_GetAggregatedMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) GetSnapshotTimeSeries(ctx context.Context, in *SnapshotTimeSeriesRequest, opts ...grpc.CallOption) (*SnapshotTimeSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotTimeSeriesResponse)
	err := c.cc.Invoke(ctx, EnclaveService_GetSnapshotTimeSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) CreateUserConnection(ctx context.Context, in *CreateUserConnectionRequest, opts ...grpc.CallOption) (*CreateUserConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserConnectionResponse)
	err := c.cc.Invoke(ctx, EnclaveService_CreateUserConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) GetPerformanceMetrics(ctx context.Context, in *PerformanceMetricsRequest, opts ...grpc.CallOption) (*PerformanceMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceMetricsResponse)
	err := c.cc.Invoke(ctx, EnclaveService_GetPerformanceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, EnclaveService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) GenerateSignedReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*SignedReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedReportResponse)
	err := c.cc.Invoke(ctx, EnclaveService_GenerateSignedReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enclaveServiceClient) VerifyReportSignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySignatureResponse)
	err := c.cc.Invoke(ctx, EnclaveService_VerifyReportSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnclaveServiceServer is the server API for EnclaveService service.
// All implementations must embed UnimplementedEnclaveServiceServer
// for forward compatibility.
//
// The Enclave service provides secure operations for trade synchronization
// and data aggregation. All operations return only aggregated, safe data.
type EnclaveServiceServer interface {
	// Process a synchronization job for a user's exchanges
	ProcessSyncJob(context.Context, *SyncJobRequest) (*SyncJobResponse, error)
	// Get aggregated metrics for a user
	GetAggregatedMetrics(context.Context, *AggregatedMetricsRequest) (*AggregatedMetricsResponse, error)
	// Get snapshot time series (daily snapshots history)
	GetSnapshotTimeSeries(context.Context, *SnapshotTimeSeriesRequest) (*SnapshotTimeSeriesResponse, error)
	// Create a user with exchange connection (auto-generates UID)
	CreateUserConnection(context.Context, *CreateUserConnectionRequest) (*CreateUserConnectionResponse, error)
	// Get performance metrics (Sharpe, volatility, drawdown, etc.)
	GetPerformanceMetrics(context.Context, *PerformanceMetricsRequest) (*PerformanceMetricsResponse, error)
	// Health check for the enclave
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Generate a cryptographically signed report
	GenerateSignedReport(context.Context, *ReportRequest) (*SignedReportResponse, error)
	// Verify a report signature
	VerifyReportSignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error)
	mustEmbedUnimplementedEnclaveServiceServer()
}

// UnimplementedEnclaveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnclaveServiceServer struct{}

func (UnimplementedEnclaveServiceServer) ProcessSyncJob(context.Context, *SyncJobRequest) (*SyncJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSyncJob not implemented")
}
func (UnimplementedEnclaveServiceServer) GetAggregatedMetrics(context.Context, *AggregatedMetricsRequest) (*AggregatedMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregatedMetrics not implemented")
}
func (UnimplementedEnclaveServiceServer) GetSnapshotTimeSeries(context.Context, *SnapshotTimeSeriesRequest) (*SnapshotTimeSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshotTimeSeries not implemented")
}
func (UnimplementedEnclaveServiceServer) CreateUserConnection(context.Context, *CreateUserConnectionRequest) (*CreateUserConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserConnection not implemented")
}
func (UnimplementedEnclaveServiceServer) GetPerformanceMetrics(context.Context, *PerformanceMetricsRequest) (*PerformanceMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerformanceMetrics not implemented")
}
func (UnimplementedEnclaveServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedEnclaveServiceServer) GenerateSignedReport(context.Context, *ReportRequest) (*SignedReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSignedReport not implemented")
}
func (UnimplementedEnclaveServiceServer) VerifyReportSignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyReportSignature not implemented")
}
func (UnimplementedEnclaveServiceServer) mustEmbedUnimplementedEnclaveServiceServer() {}
func (UnimplementedEnclaveServiceServer) testEmbeddedByValue()                        {}

// UnsafeEnclaveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnclaveServiceServer will
// result in compilation errors.
type UnsafeEnclaveServiceServer interface {
	mustEmbedUnimplementedEnclaveServiceServer()
}

func RegisterEnclaveServiceServer(s grpc.ServiceRegistrar, srv EnclaveServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnclaveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnclaveService_ServiceDesc, srv)
}

func _EnclaveService_ProcessSyncJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).ProcessSyncJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_ProcessSyncJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).ProcessSyncJob(ctx, req.(*SyncJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_GetAggregatedMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).GetAggregatedMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_GetAggregatedMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).GetAggregatedMetrics(ctx, req.(*AggregatedMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_GetSnapshotTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotTimeSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).GetSnapshotTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_GetSnapshotTimeSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).GetSnapshotTimeSeries(ctx, req.(*SnapshotTimeSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_CreateUserConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).CreateUserConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_CreateUserConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).CreateUserConnection(ctx, req.(*CreateUserConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_GetPerformanceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformanceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).GetPerformanceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_GetPerformanceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).GetPerformanceMetrics(ctx, req.(*PerformanceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_GenerateSignedReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).GenerateSignedReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_GenerateSignedReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).GenerateSignedReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnclaveService_VerifyReportSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnclaveServiceServer).VerifyReportSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnclaveService_VerifyReportSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnclaveServiceServer).VerifyReportSignature(ctx, req.(*VerifySignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnclaveService_ServiceDesc is the grpc.ServiceDesc for EnclaveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnclaveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enclave.EnclaveService",
	HandlerType: (*EnclaveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSyncJob",
			Handler:    _EnclaveService_ProcessSyncJob_Handler,
		},
		{
			MethodName: "GetAggregatedMetrics",
			Handler:    _EnclaveService_GetAggregatedMetrics_Handler,
		},
		{
			MethodName: "GetSnapshotTimeSeries",
			Handler:    _EnclaveService_GetSnapshotTimeSeries_Handler,
		},
		{
			MethodName: "CreateUserConnection",
			Handler:    _EnclaveService_CreateUserConnection_Handler,
		},
		{
			MethodName: "GetPerformanceMetrics",
			Handler:    _EnclaveService_GetPerformanceMetrics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _EnclaveService_HealthCheck_Handler,
		},
		{
			MethodName: "GenerateSignedReport",
			Handler:    _EnclaveService_GenerateSignedReport_Handler,
		},
		{
			MethodName: "VerifyReportSignature",
			Handler:    _EnclaveService_VerifyReportSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/enclave.proto",
}
