[app]
    name = enclave
    metrics = enclave.*
    private charts = yes
    gaps when not collected = yes

[dictionary]
    enclave.attestation.success = Attestation Success
    enclave.attestation.failure = Attestation Failure

[attestation]
    name = attestations
    title = SEV-SNP Attestations (per sec)
    units = req/s
    type = line
    metrics = enclave.attestation.success enclave.attestation.failure
