package grpc

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"net"
	"os"
	"strings"
	"time"

	pb "github.com/trackrecord/enclave/api/proto"
	"github.com/trackrecord/enclave/internal/attestation"
	"github.com/trackrecord/enclave/internal/auth"
	"github.com/trackrecord/enclave/internal/repository"
	"github.com/trackrecord/enclave/internal/service"
	"github.com/trackrecord/enclave/internal/signing"
	"github.com/trackrecord/enclave/internal/validation"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/reflection"
	"google.golang.org/grpc/status"
)

var startTime = time.Now()

const version = "1.0.0-go"
const genericInternalError = "Internal server error"

// msgDatabaseNotConfigured is the canonical error string returned when an
// RPC needs a DB pool but none is wired (dev harness mode). QUAL-001:
// extracted to remove a 4-way duplication across handlers.
const msgDatabaseNotConfigured = "database not configured"

// grpcMaxRecvMsgSize caps the size of a single inbound gRPC request
// (GRPC-001). 256 KiB is well above any legitimate payload (the largest
// is SignedReportRequest, a handful of date strings) and below the
// stdlib default of 4 MiB, which would let a malicious caller waste
// enclave memory cheaply.
const grpcMaxRecvMsgSize = 256 << 10

// Server implements the protobuf EnclaveService.
type Server struct {
	pb.UnimplementedEnclaveServiceServer

	logger            *zap.Logger
	connSvc           connectionService
	syncSvc           *service.SyncService
	metricsSvc        *service.MetricsService
	reportSvc         *service.ReportService
	snapshotRepo      *repository.SnapshotRepo
	userRepo          *repository.UserRepo
	attestSvc         *attestation.Service
	grpcServer        *grpc.Server
	jwtSecret         []byte // HMAC-SHA256 secret for JWT verification; nil = dev mode (no auth)
	jwtExpectedIssuer string // pins the `iss` claim when non-empty (AUTH-002)
}

type connectionService interface {
	Create(ctx context.Context, req *service.CreateConnectionRequest) error
	GetExcludedConnectionKeys(ctx context.Context, userUID string) (map[string]struct{}, error)
	GetActiveConnections(ctx context.Context, userUID string) ([]*repository.ExchangeConnection, error)
}

// ServerOptions holds optional configuration for the gRPC server.
type ServerOptions struct {
	// JWTSecret is the HMAC-SHA256 secret used to verify bearer tokens sent
	// by the frontend BFF before reaching the enclave via report-service.
	// When nil the server operates in dev mode: JWT auth is skipped with a
	// warning. In production ENCLAVE_JWT_SECRET must be set.
	JWTSecret []byte

	// JWTExpectedIssuer pins the `iss` claim required on every inbound
	// JWT (AUTH-002 follow-up). Empty leaves issuer unchecked (legacy).
	JWTExpectedIssuer string
}

// Services bundles every dependency the gRPC server needs (QUAL-001:
// extracted to keep NewServer's parameter list under SonarQube's S107
// threshold and to future-proof against further service additions).
//
// All fields are optional in the dev harness — handlers nil-check before
// dereferencing — but production wiring must populate every field.
// AttestSvc is the only field that's optional by design: when non-nil the
// server enriches signed-report responses with the current SEV-SNP launch
// measurement.
type Services struct {
	ConnSvc      connectionService
	SyncSvc      *service.SyncService
	MetricsSvc   *service.MetricsService
	ReportSvc    *service.ReportService
	SnapshotRepo *repository.SnapshotRepo
	UserRepo     *repository.UserRepo
	AttestSvc    *attestation.Service
}

// NewServer creates a new gRPC server.
//
// AttestSvc inside svcs is optional: if non-nil, the server enriches signed
// report responses with the current SEV-SNP launch measurement so clients
// can prove the report was generated by a specific audited build.
func NewServer(logger *zap.Logger, svcs Services, opts ServerOptions) *Server {
	return &Server{
		logger:            logger,
		connSvc:           svcs.ConnSvc,
		syncSvc:           svcs.SyncSvc,
		metricsSvc:        svcs.MetricsSvc,
		reportSvc:         svcs.ReportSvc,
		snapshotRepo:      svcs.SnapshotRepo,
		userRepo:          svcs.UserRepo,
		attestSvc:         svcs.AttestSvc,
		jwtSecret:         opts.JWTSecret,
		jwtExpectedIssuer: opts.JWTExpectedIssuer,
	}
}

// Start starts the gRPC server. If tlsConfig is nil, the server runs in insecure mode.
func (s *Server) Start(port int, tlsConfig *tls.Config) error {
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		return fmt.Errorf("failed to listen: %w", err)
	}

	serverOpts := []grpc.ServerOption{
		grpc.ChainUnaryInterceptor(s.authInterceptor, s.loggingInterceptor),
		// GRPC-001: cap inbound message size at 256 KiB. The largest
		// legitimate payload is the SignedReportRequest (a few date / flag
		// fields) — REST applies a 64 KiB MaxBytesReader on the same
		// surface; we leave a wider margin here for the metric / snapshot
		// responses that flow back over the same gRPC connections.
		grpc.MaxRecvMsgSize(grpcMaxRecvMsgSize),
	}
	if tlsConfig != nil {
		serverOpts = append(serverOpts, grpc.Creds(credentials.NewTLS(tlsConfig)))
	}

	s.grpcServer = grpc.NewServer(serverOpts...)
	pb.RegisterEnclaveServiceServer(s.grpcServer, s)
	// Reflection exposes the full service schema to anyone who can reach the
	// port. Gate it on !production so dev/test tooling (grpcurl, Postman)
	// keeps working while production deployments do not hand out introspection.
	if !s.isProduction() {
		reflection.Register(s.grpcServer)
	}

	mode := "insecure"
	if tlsConfig != nil {
		mode = "tls"
	}
	s.logger.Info("gRPC server starting",
		zap.Int("port", port),
		zap.String("mode", mode),
		zap.Bool("reflection", !s.isProduction()),
	)
	return s.grpcServer.Serve(lis)
}

// Stop gracefully stops the server.
func (s *Server) Stop() {
	if s.grpcServer != nil {
		s.grpcServer.GracefulStop()
	}
}

func (s *Server) loggingInterceptor(
	ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (interface{}, error) {
	start := time.Now()
	resp, err := handler(ctx, req)
	s.logger.Info("grpc request",
		zap.String("method", info.FullMethod),
		zap.Duration("duration", time.Since(start)),
		zap.Error(err),
	)
	return resp, err
}

// methodsRequireJWT lists gRPC methods where the JWT bearer is the source of
// truth for the authenticated user. AUTH-002: every RPC that accepts a
// `user_uid` argument is gated here, not just GenerateSignedReport.
// Previous design trusted the gateway for per-user authorization; a
// compromised report-service / BFF could then pass an arbitrary user_uid
// on any of these calls. Handlers below pair this with resolveUserUID()
// so claims.Sub wins over req.UserUid whenever the JWT is verified.
var methodsRequireJWT = map[string]bool{
	"/enclave.EnclaveService/GenerateSignedReport":  true,
	"/enclave.EnclaveService/CreateUserConnection":  true,
	"/enclave.EnclaveService/ProcessSyncJob":        true,
	"/enclave.EnclaveService/GetPerformanceMetrics": true,
	"/enclave.EnclaveService/GetSnapshotTimeSeries": true,
	"/enclave.EnclaveService/GetAggregatedMetrics":  true,
}

// resolveUserUID returns the authenticated caller UID (AUTH-002). When
// authInterceptor has verified a bearer token it injects claims.Sub into
// ctx via auth.WithUserUID; we prefer that value over whatever the client
// wrote in the request message. The req-supplied value is used only in dev
// mode (when ENCLAVE_JWT_SECRET is unset and authInterceptor skips auth).
func resolveUserUID(ctx context.Context, reqUID string) string {
	if uid, ok := auth.UserUIDFromContext(ctx); ok {
		return uid
	}
	return reqUID
}

// authInterceptor verifies the JWT bearer token in gRPC metadata.
//
// When jwtSecret is set (production), methods in methodsRequireJWT must carry
// a valid Authorization: Bearer <jwt> header. The JWT sub claim is stored in
// the context so handlers can use it instead of trusting the user_uid field
// in the request message.
//
// When jwtSecret is nil (dev mode), auth is skipped with a warning so local
// development works without environment setup.
func (s *Server) authInterceptor(
	ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (interface{}, error) {
	if !methodsRequireJWT[info.FullMethod] {
		return handler(ctx, req)
	}

	if len(s.jwtSecret) == 0 {
		s.logger.Warn("JWT auth skipped (ENCLAVE_JWT_SECRET not set)",
			zap.String("method", info.FullMethod),
		)
		return handler(ctx, req)
	}

	// Extract Authorization header from gRPC metadata
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, status.Error(codes.Unauthenticated, "missing metadata")
	}

	authValues := md.Get("authorization")
	if len(authValues) == 0 {
		return nil, status.Error(codes.Unauthenticated, "missing authorization header")
	}

	tokenStr := strings.TrimPrefix(authValues[0], "Bearer ")
	if tokenStr == authValues[0] {
		return nil, status.Error(codes.Unauthenticated, "authorization header must use Bearer scheme")
	}

	claims, err := auth.VerifyHS256WithOptions(tokenStr, s.jwtSecret, auth.VerifyOptions{
		ExpectedIssuer: s.jwtExpectedIssuer,
	})
	if err != nil {
		s.logger.Warn("JWT verification failed",
			zap.String("method", info.FullMethod),
			zap.Error(err),
		)
		return nil, status.Error(codes.Unauthenticated, "invalid or expired token")
	}

	// Inject verified user UID into context — handlers must use this, not req.UserUid
	ctx = auth.WithUserUID(ctx, claims.Sub)
	return handler(ctx, req)
}

func (s *Server) isProduction() bool {
	env := strings.ToLower(os.Getenv("ENV"))
	nodeEnv := strings.ToLower(os.Getenv("NODE_ENV"))
	return env == "production" || nodeEnv == "production"
}

func (s *Server) sanitizeErrorForClient(err error) string {
	if err == nil {
		return ""
	}
	return s.sanitizeMessageForClient(err.Error())
}

// userFacingErrorPatterns are substrings that mark an error message as safe
// to surface to the end-user even in production. These describe a category
// of failure the user can act on (wrong credentials, typo in server name,
// IP not whitelisted, etc.) without leaking infrastructure details — they
// never carry file paths, internal hostnames, IPs, or stack traces.
//
// Anything not matching these is replaced by the generic "Internal server
// error" message in production to avoid leaking implementation specifics.
var userFacingErrorPatterns = []string{
	"invalid credentials",
	"invalid api key",
	"invalid signature",
	"auth_failed",
	"unauthorized",
	"no such host",
	"connection refused",
	"deadline exceeded",
	"timeout",
	"ip not whitelist",
	"ip restricted",
	"whitelist",
	"permission denied",
	"insufficient permission",
	"validation failed",
	"protocol_error",
	"failed to create connection",
	"failed to create user",
	"database not configured",
	"service not available",
	"sync service not available",
	"report service not available",
	"already exists",
	"not found",
}

func (s *Server) sanitizeMessageForClient(msg string) string {
	if msg == "" {
		return ""
	}
	if !s.isProduction() {
		return msg
	}
	lower := strings.ToLower(msg)
	for _, p := range userFacingErrorPatterns {
		if strings.Contains(lower, p) {
			return msg
		}
	}
	return genericInternalError
}

func currentEnclaveMode() string {
	env := strings.ToLower(os.Getenv("ENV"))
	nodeEnv := strings.ToLower(os.Getenv("NODE_ENV"))
	if env == "production" || nodeEnv == "production" {
		return "production"
	}
	return "development"
}

// HealthCheck implements EnclaveService.
// Verifies database connectivity (TS parity).
func (s *Server) HealthCheck(ctx context.Context, req *pb.HealthCheckRequest) (*pb.HealthCheckResponse, error) {
	uptime := time.Since(startTime).Seconds()

	st := pb.HealthCheckResponse_HEALTHY
	if s.snapshotRepo != nil {
		// Test DB connectivity by running a lightweight query
		_, err := s.snapshotRepo.GetByUserAndDateRange(ctx, "__healthcheck__",
			time.Now().Add(-time.Hour), time.Now())
		if err != nil {
			s.logger.Error("health check failed - database connectivity issue", zap.Error(err))
			st = pb.HealthCheckResponse_UNHEALTHY
		}
	}

	return &pb.HealthCheckResponse{
		Status:  st,
		Enclave: true,
		Version: version,
		Uptime:  uptime,
	}, nil
}

// CreateUserConnection implements EnclaveService.
func (s *Server) CreateUserConnection(ctx context.Context, req *pb.CreateUserConnectionRequest) (*pb.CreateUserConnectionResponse, error) {
	// AUTH-002: prefer the JWT-verified uid over the body-supplied one.
	userUID := resolveUserUID(ctx, req.UserUid)

	if err := validation.ValidateCreateConnection(&validation.CreateConnectionRequest{
		UserUID:    userUID,
		Exchange:   req.Exchange,
		Label:      req.Label,
		APIKey:     req.ApiKey,
		APISecret:  req.ApiSecret,
		Passphrase: req.Passphrase,
	}); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	if s.connSvc == nil {
		return &pb.CreateUserConnectionResponse{
			Success: false,
			UserUid: userUID,
			Error:   s.sanitizeMessageForClient(msgDatabaseNotConfigured),
		}, nil
	}

	if s.userRepo != nil {
		if _, err := s.userRepo.GetOrCreate(ctx, userUID); err != nil {
			s.logger.Error("user upsert failed", zap.Error(err))
			return &pb.CreateUserConnectionResponse{
				Success: false,
				UserUid: userUID,
				Error:   s.sanitizeMessageForClient("failed to create user"),
			}, nil
		}
	}

	err := s.connSvc.Create(ctx, &service.CreateConnectionRequest{
		UserUID:           userUID,
		Exchange:          req.Exchange,
		Label:             req.Label,
		APIKey:            req.ApiKey,
		APISecret:         req.ApiSecret,
		Passphrase:        req.Passphrase,
		ExcludeFromReport: req.ExcludeFromReport,
	})
	if err != nil {
		if errors.Is(err, service.ErrConnectionAlreadyExists) {
			return &pb.CreateUserConnectionResponse{
				Success: true,
				UserUid: userUID,
				Error:   service.ExistingConnectionNoopMessage,
			}, nil
		}
		s.logger.Error("create connection failed", zap.Error(err))
		return &pb.CreateUserConnectionResponse{
			Success: false,
			UserUid: userUID,
			// Pass the real cause: sanitizeErrorForClient routes it through
			// the whitelist so well-known user-facing patterns (invalid
			// credentials, no such host, timeout, …) reach the client while
			// anything else collapses to the generic message.
			Error: s.sanitizeErrorForClient(err),
		}, nil
	}

	return &pb.CreateUserConnectionResponse{Success: true, UserUid: userUID}, nil
}

// ProcessSyncJob implements EnclaveService.
func (s *Server) ProcessSyncJob(ctx context.Context, req *pb.SyncJobRequest) (*pb.SyncJobResponse, error) {
	// AUTH-002: prefer the JWT-verified uid over the body-supplied one.
	userUID := resolveUserUID(ctx, req.UserUid)
	rawExchange := req.Exchange

	if err := validation.ValidateSyncRequest(&validation.SyncJobRequest{
		UserUID:  userUID,
		Exchange: rawExchange,
	}); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	exchange := strings.ToLower(rawExchange)

	if s.syncSvc == nil {
		return &pb.SyncJobResponse{
			Success:  false,
			UserUid:  userUID,
			Exchange: exchange,
			Error:    s.sanitizeMessageForClient("sync service not available"),
		}, nil
	}

	var (
		results []*service.SyncResult
		err     error
	)
	if exchange != "" {
		results = []*service.SyncResult{s.syncSvc.SyncExchange(ctx, userUID, exchange)}
	} else {
		results, err = s.syncSvc.SyncUser(ctx, userUID)
		if err != nil {
			return &pb.SyncJobResponse{
				Success:  false,
				UserUid:  userUID,
				Exchange: exchange,
				Error:    s.sanitizeErrorForClient(err),
			}, nil
		}
	}

	if len(results) == 0 {
		return &pb.SyncJobResponse{Success: false, UserUid: userUID, Error: "no results"}, nil
	}

	success, synced, snapshotsGenerated, latestSnapshot, resultErr := aggregateSyncResultsForSyncJobResponse(results)
	if resultErr != "" {
		resultErr = s.sanitizeMessageForClient(resultErr)
	}

	return &pb.SyncJobResponse{
		Success:            success,
		UserUid:            userUID,
		Exchange:           exchange,
		Synced:             synced,
		SnapshotsGenerated: snapshotsGenerated,
		LatestSnapshot:     latestSnapshot,
		Error:              resultErr,
	}, nil
}

// GetPerformanceMetrics implements EnclaveService.
func (s *Server) GetPerformanceMetrics(ctx context.Context, req *pb.PerformanceMetricsRequest) (*pb.PerformanceMetricsResponse, error) {
	if s.metricsSvc == nil {
		return &pb.PerformanceMetricsResponse{Success: false, Error: "metrics service not available"}, nil
	}
	// AUTH-002: prefer the JWT-verified uid over the body-supplied one.
	userUID := resolveUserUID(ctx, req.UserUid)
	rawExchange := req.Exchange

	if err := validation.ValidateUserUID(userUID); err != nil {
		return &pb.PerformanceMetricsResponse{Success: false, Error: err.Error()}, nil
	}
	if rawExchange != "" {
		if err := validation.ValidateExchange(rawExchange); err != nil {
			return &pb.PerformanceMetricsResponse{Success: false, Error: err.Error()}, nil
		}
	}
	exchange := strings.ToLower(rawExchange)

	start := time.UnixMilli(req.StartDate)
	end := time.UnixMilli(req.EndDate)
	if req.StartDate == 0 {
		start = time.Now().AddDate(-1, 0, 0)
	}
	if req.EndDate == 0 {
		end = time.Now()
	}

	excludedConnectionKeys := map[string]struct{}{}
	if s.connSvc != nil {
		excluded, err := s.connSvc.GetExcludedConnectionKeys(ctx, userUID)
		if err != nil {
			return &pb.PerformanceMetricsResponse{Success: false, Error: s.sanitizeErrorForClient(err)}, nil
		}
		excludedConnectionKeys = excluded
	}

	metrics, err := s.metricsSvc.CalculateWithFilters(ctx, userUID, start, end, exchange, excludedConnectionKeys)
	if err != nil {
		return &pb.PerformanceMetricsResponse{Success: false, Error: s.sanitizeErrorForClient(err)}, nil
	}

	return &pb.PerformanceMetricsResponse{
		SharpeRatio:         metrics.SharpeRatio,
		SortinoRatio:        metrics.SortinoRatio,
		CalmarRatio:         metrics.CalmarRatio,
		Volatility:          metrics.Volatility,
		DownsideDeviation:   metrics.DownsideDeviation,
		MaxDrawdown:         metrics.MaxDrawdown,
		MaxDrawdownDuration: int32(metrics.MaxDrawdownDuration),
		CurrentDrawdown:     metrics.CurrentDrawdown,
		WinRate:             metrics.WinRate,
		ProfitFactor:        metrics.ProfitFactor,
		AvgWin:              metrics.AvgWin,
		AvgLoss:             metrics.AvgLoss,
		PeriodStart:         metrics.PeriodStart.UnixMilli(),
		PeriodEnd:           metrics.PeriodEnd.UnixMilli(),
		DataPoints:          int32(metrics.DataPoints),
		Success:             true,
	}, nil
}

// GetSnapshotTimeSeries implements EnclaveService.
func (s *Server) GetSnapshotTimeSeries(ctx context.Context, req *pb.SnapshotTimeSeriesRequest) (*pb.SnapshotTimeSeriesResponse, error) {
	if s.snapshotRepo == nil {
		return nil, status.Error(codes.Unavailable, msgDatabaseNotConfigured)
	}
	// AUTH-002: prefer the JWT-verified uid over the body-supplied one.
	userUID := resolveUserUID(ctx, req.UserUid)
	rawExchange := req.Exchange

	if err := validation.ValidateUserUID(userUID); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	if rawExchange != "" {
		if err := validation.ValidateExchange(rawExchange); err != nil {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
	}
	if err := validation.ValidateOptionalTimestampMillis(req.StartDate, "start_date"); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	if err := validation.ValidateOptionalTimestampMillis(req.EndDate, "end_date"); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	if req.StartDate != 0 && req.EndDate != 0 {
		if req.StartDate >= req.EndDate {
			return nil, status.Error(codes.InvalidArgument, "end_date must be after start_date")
		}
		if err := validation.ValidateTimestampRange(time.UnixMilli(req.StartDate), time.UnixMilli(req.EndDate)); err != nil {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
	}
	exchange := strings.ToLower(rawExchange)

	start := time.UnixMilli(req.StartDate)
	end := time.UnixMilli(req.EndDate)
	if req.StartDate == 0 {
		start = time.Now().AddDate(-1, 0, 0)
	}
	if req.EndDate == 0 {
		end = time.Now()
	}

	snapshots, err := s.snapshotRepo.GetByUserAndDateRange(ctx, userUID, start, end)
	if err != nil {
		return nil, status.Error(codes.Internal, s.sanitizeErrorForClient(err))
	}

	excludedConnectionKeys := map[string]struct{}{}
	if s.connSvc != nil {
		excluded, err := s.connSvc.GetExcludedConnectionKeys(ctx, userUID)
		if err != nil {
			return nil, status.Error(codes.Internal, s.sanitizeErrorForClient(err))
		}
		excludedConnectionKeys = excluded
	}

	resp := &pb.SnapshotTimeSeriesResponse{Snapshots: make([]*pb.DailySnapshot, 0, len(snapshots))}
	for _, snap := range snapshots {
		if isConnectionExcluded(excludedConnectionKeys, snap.Exchange, snap.Label) {
			continue
		}
		if exchange != "" && strings.ToLower(snap.Exchange) != exchange {
			continue
		}
		resp.Snapshots = append(resp.Snapshots, &pb.DailySnapshot{
			UserUid:         snap.UserUID,
			Exchange:        snap.Exchange,
			Timestamp:       snap.Timestamp.UnixMilli(),
			TotalEquity:     snap.TotalEquity,
			RealizedBalance: snap.RealizedBalance,
			UnrealizedPnl:   snap.UnrealizedPnL,
			Deposits:        snap.Deposits,
			Withdrawals:     snap.Withdrawals,
			Breakdown:       mapMarketBreakdown(snap.Breakdown),
		})
	}

	return resp, nil
}

// GetAggregatedMetrics implements EnclaveService.
func (s *Server) GetAggregatedMetrics(ctx context.Context, req *pb.AggregatedMetricsRequest) (*pb.AggregatedMetricsResponse, error) {
	if s.snapshotRepo == nil {
		return nil, status.Error(codes.Unavailable, msgDatabaseNotConfigured)
	}
	// AUTH-002: prefer the JWT-verified uid over the body-supplied one.
	userUID := resolveUserUID(ctx, req.UserUid)
	rawExchange := req.Exchange

	if err := validation.ValidateUserUID(userUID); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	if rawExchange != "" {
		if err := validation.ValidateExchange(rawExchange); err != nil {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
	}
	exchange := strings.ToLower(rawExchange)

	if s.connSvc == nil {
		snapshot, err := s.snapshotRepo.GetLatestByUser(ctx, userUID)
		if err != nil {
			return &pb.AggregatedMetricsResponse{}, nil
		}
		return &pb.AggregatedMetricsResponse{
			TotalBalance:       snapshot.RealizedBalance,
			TotalEquity:        snapshot.TotalEquity,
			TotalUnrealizedPnl: snapshot.UnrealizedPnL,
			TotalFees:          snapshot.TotalFees,
			TotalTrades:        int32(snapshot.TotalTrades),
			LastSync:           snapshot.Timestamp.UnixMilli(),
		}, nil
	}

	excludedConnectionKeys, err := s.connSvc.GetExcludedConnectionKeys(ctx, userUID)
	if err != nil {
		return nil, status.Error(codes.Internal, s.sanitizeErrorForClient(err))
	}

	connections, err := s.connSvc.GetActiveConnections(ctx, userUID)
	if err != nil || len(connections) == 0 {
		return &pb.AggregatedMetricsResponse{}, nil
	}

	resp := &pb.AggregatedMetricsResponse{}
	var lastSync time.Time

	for _, conn := range connections {
		if isConnectionExcluded(excludedConnectionKeys, conn.Exchange, conn.Label) {
			continue
		}
		if exchange != "" && strings.ToLower(conn.Exchange) != exchange {
			continue
		}

		snapshot, err := s.snapshotRepo.GetLatestByUserExchangeLabel(ctx, userUID, conn.Exchange, conn.Label)
		if err != nil {
			continue
		}

		resp.TotalBalance += snapshot.RealizedBalance
		resp.TotalEquity += snapshot.TotalEquity
		resp.TotalUnrealizedPnl += snapshot.UnrealizedPnL
		resp.TotalFees += snapshot.TotalFees
		resp.TotalTrades += int32(snapshot.TotalTrades)

		if snapshot.Timestamp.After(lastSync) {
			lastSync = snapshot.Timestamp
		}
	}

	if !lastSync.IsZero() {
		resp.LastSync = lastSync.UnixMilli()
	}

	return resp, nil
}

// GenerateSignedReport implements EnclaveService.
func (s *Server) GenerateSignedReport(ctx context.Context, req *pb.ReportRequest) (*pb.SignedReportResponse, error) {
	if s.reportSvc == nil {
		return &pb.SignedReportResponse{Success: false, Error: "report service not available"}, nil
	}

	// AUTH-002: prefer the JWT-verified uid over the body-supplied one.
	// This prevents IDOR: an attacker who controls report-service cannot
	// request data for an arbitrary user by setting req.UserUid to a victim's
	// uid. Shared helper with the rest of the RPCs — see resolveUserUID.
	userUID := resolveUserUID(ctx, req.UserUid)

	if err := validation.ValidateReportRequest(&validation.ReportRequest{
		UserUID:   userUID,
		StartDate: req.StartDate,
		EndDate:   req.EndDate,
		Benchmark: req.Benchmark,
	}); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}

	var (
		startDate time.Time
		endDate   time.Time
		err       error
	)

	if req.StartDate != "" {
		startDate, err = time.Parse("2006-01-02", req.StartDate)
		if err != nil {
			return nil, status.Error(codes.InvalidArgument, "invalid start_date format (use YYYY-MM-DD)")
		}
	}
	if req.EndDate != "" {
		endDate, err = time.Parse("2006-01-02", req.EndDate)
		if err != nil {
			return nil, status.Error(codes.InvalidArgument, "invalid end_date format (use YYYY-MM-DD)")
		}
	}

	excludedConnectionKeys := map[string]struct{}{}
	if s.connSvc != nil {
		excluded, err := s.connSvc.GetExcludedConnectionKeys(ctx, userUID)
		if err != nil {
			return &pb.SignedReportResponse{Success: false, Error: s.sanitizeErrorForClient(err)}, nil
		}
		excludedConnectionKeys = excluded
	}

	if startDate.IsZero() || endDate.IsZero() {
		defaultStart, defaultEnd, err := s.resolveReportPeriod(ctx, userUID, excludedConnectionKeys, startDate, endDate)
		if err != nil {
			return &pb.SignedReportResponse{Success: false, Error: s.sanitizeErrorForClient(err)}, nil
		}
		if startDate.IsZero() {
			startDate = defaultStart
		}
		if endDate.IsZero() {
			endDate = defaultEnd
		}
	}

	report, err := s.reportSvc.GenerateReport(ctx, &service.GenerateReportRequest{
		UserUID:            userUID,
		StartDate:          startDate,
		EndDate:            endDate,
		ReportName:         req.ReportName,
		Benchmark:          req.Benchmark,
		BaseCurrency:       req.BaseCurrency,
		IncludeRiskMetrics: req.IncludeRiskMetrics,
		IncludeDrawdown:    req.IncludeDrawdown,
		ExcludedExchanges:  excludedConnectionKeys,
		Manager:            "",
		Firm:               "",
	})
	if err != nil {
		s.logger.Error("generate report failed", zap.Error(err))
		return &pb.SignedReportResponse{Success: false, Error: s.sanitizeErrorForClient(err)}, nil
	}

	resp := &pb.SignedReportResponse{
		Success:            true,
		ReportId:           report.ReportID,
		UserUid:            report.UserUID,
		ReportName:         report.ReportName,
		GeneratedAt:        report.GeneratedAt,
		PeriodStart:        report.PeriodStart,
		PeriodEnd:          report.PeriodEnd,
		BaseCurrency:       report.BaseCurrency,
		Benchmark:          report.Benchmark,
		DataPoints:         int32(report.DataPoints),
		Exchanges:          report.Exchanges,
		TotalReturn:        report.TotalReturn,
		AnnualizedReturn:   report.AnnualizedReturn,
		Volatility:         report.Volatility,
		SharpeRatio:        report.SharpeRatio,
		SortinoRatio:       report.SortinoRatio,
		MaxDrawdown:        report.MaxDrawdown,
		CalmarRatio:        report.CalmarRatio,
		Signature:          report.Signature,
		PublicKey:          report.PublicKey,
		SignatureAlgorithm: report.SignatureAlgorithm,
		ReportHash:         report.ReportHash,
		EnclaveVersion:     report.EnclaveVersion,
		EnclaveMode:        currentEnclaveMode(),
	}
	resp.ExchangeDetails = mapExchangeDetails(report.ExchangeDetails, report.Exchanges)

	// SEC-107: resp.Measurement is deliberately left empty. The previous code
	// attached the current measurement OUTSIDE the signed payload, which let
	// a MitM swap the value without invalidating the signature. Clients must
	// read the measurement from the signed EnclaveAttestation block inside
	// the report payload (verifiable via reportverify.Verifier). The proto
	// field is kept for backward compatibility and will be removed once all
	// known callers have migrated.

	if len(report.DailyReturns) > 0 {
		resp.DailyReturns = make([]*pb.DailyReturnData, 0, len(report.DailyReturns))
		for _, dr := range report.DailyReturns {
			resp.DailyReturns = append(resp.DailyReturns, &pb.DailyReturnData{
				Date:             dr.Date,
				NetReturn:        dr.NetReturn,
				BenchmarkReturn:  dr.BenchmarkReturn,
				Outperformance:   dr.Outperformance,
				CumulativeReturn: dr.CumulativeReturn,
				Nav:              dr.NAV,
			})
		}
	}

	if len(report.MonthlyReturns) > 0 {
		resp.MonthlyReturns = make([]*pb.MonthlyReturnData, 0, len(report.MonthlyReturns))
		for _, mr := range report.MonthlyReturns {
			resp.MonthlyReturns = append(resp.MonthlyReturns, &pb.MonthlyReturnData{
				Date:            mr.Date,
				NetReturn:       mr.NetReturn,
				BenchmarkReturn: mr.BenchmarkReturn,
				Outperformance:  mr.Outperformance,
				Aum:             mr.AUM,
			})
		}
	}

	if report.RiskMetrics != nil {
		resp.Var_95 = report.RiskMetrics.VaR95
		resp.Var_99 = report.RiskMetrics.VaR99
		resp.ExpectedShortfall = report.RiskMetrics.ExpectedShortfall
		resp.Skewness = report.RiskMetrics.Skewness
		resp.Kurtosis = report.RiskMetrics.Kurtosis
	}

	if report.BenchmarkMetrics != nil {
		resp.Alpha = report.BenchmarkMetrics.Alpha
		resp.Beta = report.BenchmarkMetrics.Beta
		resp.InformationRatio = report.BenchmarkMetrics.InformationRatio
		resp.TrackingError = report.BenchmarkMetrics.TrackingError
		resp.Correlation = report.BenchmarkMetrics.Correlation
	}

	if report.DrawdownData != nil {
		resp.CurrentDrawdown = report.DrawdownData.CurrentDrawdown
		resp.MaxDrawdownDuration = int32(report.DrawdownData.MaxDrawdownDuration)
		resp.DrawdownPeriods = make([]*pb.DrawdownPeriodData, 0, len(report.DrawdownData.Periods))
		for _, p := range report.DrawdownData.Periods {
			resp.DrawdownPeriods = append(resp.DrawdownPeriods, &pb.DrawdownPeriodData{
				StartDate: p.StartDate,
				EndDate:   p.EndDate,
				Depth:     p.Depth,
				Duration:  int32(p.Duration),
				Recovered: p.Recovered,
			})
		}
	}

	return resp, nil
}

// VerifyReportSignature implements EnclaveService.
func (s *Server) VerifyReportSignature(ctx context.Context, req *pb.VerifySignatureRequest) (*pb.VerifySignatureResponse, error) {
	if s.reportSvc == nil {
		return nil, status.Error(codes.Internal, s.sanitizeMessageForClient("report service not available"))
	}
	if req.ReportHash == "" || req.Signature == "" || req.PublicKey == "" {
		return nil, status.Error(codes.InvalidArgument, "report_hash, signature, and public_key are required")
	}

	valid, err := s.reportSvc.VerifySignature(req.ReportHash, req.Signature, req.PublicKey)
	if err != nil {
		return nil, status.Error(codes.Internal, s.sanitizeErrorForClient(err))
	}

	return &pb.VerifySignatureResponse{Valid: valid}, nil
}

// resolveReportPeriod returns the effective [start,end] period from snapshots.
// This mirrors TS behavior where report dates are optional:
// - no dates => first and last available snapshot
// - one date => infer the missing bound from available snapshots in that range
func (s *Server) resolveReportPeriod(
	ctx context.Context,
	userUID string,
	excludedConnectionKeys map[string]struct{},
	startHint time.Time,
	endHint time.Time,
) (time.Time, time.Time, error) {
	if s.snapshotRepo == nil {
		return time.Time{}, time.Time{}, errors.New(msgDatabaseNotConfigured)
	}

	rangeStart := time.Unix(0, 0).UTC()
	rangeEnd := time.Now().UTC().AddDate(100, 0, 0)

	if !startHint.IsZero() {
		rangeStart = startHint
	}
	if !endHint.IsZero() {
		rangeEnd = endHint
	}
	if rangeEnd.Before(rangeStart) {
		return time.Time{}, time.Time{}, fmt.Errorf("end_date must be after start_date")
	}

	snapshots, err := s.snapshotRepo.GetByUserAndDateRange(ctx, userUID, rangeStart, rangeEnd)
	if err != nil {
		return time.Time{}, time.Time{}, err
	}

	var (
		earliest time.Time
		latest   time.Time
	)
	for _, snap := range snapshots {
		if isConnectionExcluded(excludedConnectionKeys, snap.Exchange, snap.Label) {
			continue
		}
		if earliest.IsZero() || snap.Timestamp.Before(earliest) {
			earliest = snap.Timestamp
		}
		if latest.IsZero() || snap.Timestamp.After(latest) {
			latest = snap.Timestamp
		}
	}

	if earliest.IsZero() || latest.IsZero() {
		return time.Time{}, time.Time{}, fmt.Errorf("no snapshot data found for the specified period")
	}

	return earliest, latest, nil
}

func mapMarketBreakdown(in *repository.MarketBreakdown) *pb.MarketBreakdown {
	if in == nil {
		return nil
	}

	global := aggregateMarketMetrics(
		in.Stocks,
		in.Spot,
		in.Swap,
		in.Options,
		in.Futures,
		in.CFD,
		in.Forex,
		in.Commodities,
		in.Margin,
		in.Earn,
	)

	return &pb.MarketBreakdown{
		Global:      global,
		Spot:        mapMarketMetrics(in.Spot),
		Swap:        mapMarketMetrics(in.Swap),
		Options:     mapMarketMetrics(in.Options),
		Stocks:      mapMarketMetrics(in.Stocks),
		Futures:     mapMarketMetrics(in.Futures),
		Cfd:         mapMarketMetrics(in.CFD),
		Forex:       mapMarketMetrics(in.Forex),
		Commodities: mapMarketMetrics(in.Commodities),
	}
}

func connectionKey(exchange, label string) string {
	ex := strings.ToLower(strings.TrimSpace(exchange))
	lb := strings.ToLower(strings.TrimSpace(label))
	if lb == "" {
		return ex
	}
	return ex + "/" + lb
}

func isConnectionExcluded(excluded map[string]struct{}, exchange, label string) bool {
	if len(excluded) == 0 {
		return false
	}
	if _, ok := excluded[connectionKey(exchange, label)]; ok {
		return true
	}
	_, ok := excluded[strings.ToLower(strings.TrimSpace(exchange))]
	return ok
}

func mapMarketMetrics(in *repository.MarketMetrics) *pb.MarketMetrics {
	if in == nil {
		return nil
	}
	return &pb.MarketMetrics{
		Equity:          in.Equity,
		AvailableMargin: in.AvailableMargin,
		Volume:          in.Volume,
		Trades:          int32(in.Trades),
		TradingFees:     in.TradingFees,
		FundingFees:     in.FundingFees,
		LongTrades:      int32(in.LongTrades),
		ShortTrades:     int32(in.ShortTrades),
		LongVolume:      in.LongVolume,
		ShortVolume:     in.ShortVolume,
	}
}

func aggregateMarketMetrics(metrics ...*repository.MarketMetrics) *pb.MarketMetrics {
	out := &pb.MarketMetrics{}
	hasData := false
	for _, m := range metrics {
		if m == nil {
			continue
		}
		hasData = true
		out.Equity += m.Equity
		out.AvailableMargin += m.AvailableMargin
		out.Volume += m.Volume
		out.Trades += int32(m.Trades)
		out.TradingFees += m.TradingFees
		out.FundingFees += m.FundingFees
		out.LongTrades += int32(m.LongTrades)
		out.ShortTrades += int32(m.ShortTrades)
		out.LongVolume += m.LongVolume
		out.ShortVolume += m.ShortVolume
	}
	if !hasData {
		return nil
	}
	return out
}

func mapExchangeDetails(details []signing.ExchangeInfo, exchanges []string) []*pb.ExchangeInfo {
	if len(details) > 0 {
		out := make([]*pb.ExchangeInfo, 0, len(details))
		for _, ex := range details {
			out = append(out, &pb.ExchangeInfo{
				Name:     ex.Name,
				KycLevel: ex.KYCLevel,
				IsPaper:  ex.IsPaper,
			})
		}
		return out
	}

	if len(exchanges) == 0 {
		return nil
	}

	// Backward-compatible fallback for cached reports generated before exchange_details support.
	out := make([]*pb.ExchangeInfo, 0, len(exchanges))
	for _, ex := range exchanges {
		out = append(out, &pb.ExchangeInfo{
			Name:     ex,
			KycLevel: "",
			IsPaper:  false,
		})
	}
	return out
}

func aggregateSyncResultsForSyncJobResponse(results []*service.SyncResult) (bool, int32, int32, *pb.SyncJobResponse_Snapshot, string) {
	if len(results) == 0 {
		return false, 0, 0, nil, "no results"
	}

	var (
		success          bool
		synced           int32
		snapshots        int32
		latestSnapshot   *pb.SyncJobResponse_Snapshot
		latestTimestamp  time.Time
		aggregatedErrors []string
	)

	for _, r := range results {
		if r == nil {
			continue
		}

		if r.Success {
			success = true
			synced += int32(r.TradeCount)
			snapshots++
			if latestSnapshot == nil || r.SnapshotTimestamp.After(latestTimestamp) {
				latestTimestamp = r.SnapshotTimestamp
				latestSnapshot = &pb.SyncJobResponse_Snapshot{
					Balance:   r.SnapshotEquity,
					Equity:    r.SnapshotEquity,
					Timestamp: r.SnapshotTimestamp.UnixMilli(),
				}
			}
		}

		if r.Error != "" {
			if r.Label != "" {
				aggregatedErrors = append(aggregatedErrors, fmt.Sprintf("%s/%s: %s", r.Exchange, r.Label, r.Error))
			} else if r.Exchange != "" {
				aggregatedErrors = append(aggregatedErrors, fmt.Sprintf("%s: %s", r.Exchange, r.Error))
			} else {
				aggregatedErrors = append(aggregatedErrors, r.Error)
			}
		}
	}

	if !success && len(aggregatedErrors) == 0 {
		aggregatedErrors = append(aggregatedErrors, "sync failed for all connections")
	}

	return success, synced, snapshots, latestSnapshot, strings.Join(aggregatedErrors, " | ")
}
